#!/bin/bash

PREBUILT_PATH="vendor/oneplus/"

list="
bin
sbin
etc
etc/acdbdata/MTP
etc/camera
etc/cne
etc/cne/wqeclient
etc/cne/wqeclient/ATT
etc/cne/wqeclient/ROW
etc/cne/wqeclient/VZW
etc/data
etc/dpm
etc/dpm/nsrm
etc/drc
etc/firmware
etc/firmware/hbtp
etc/hostapd
etc/init
etc/mmi
etc/mmi/layout
etc/perf
etc/permissions
etc/qvop
etc/sensors
etc/surround_sound
etc/surround_sound_3mic
etc/usf
etc/usf/mixer
etc/usf/proximity
etc/usf/proximity/cfg_mtp
framework
lib
lib64
lib64/hw
lib64/soundfx
lib/hw
lib/modules
lib/rfsa/adsp
lib/soundfx
vendor
vendor/bin
vendor/bin/hw
vendor/bin/qmi-framework-tests
vendor/etc
vendor/etc/data
vendor/etc/drc
vendor/etc/init
vendor/etc/perf
vendor/etc/qvr
vendor/etc/RIDL
vendor/etc/scve/facereco
vendor/etc/scve/textreco/chardecoder
vendor/etc/scve/textreco/textdetector
vendor/etc/scve/textreco/worddecoder
vendor/etc/sensors
vendor/etc/surround_sound_3mic
vendor/etc/wifi
vendor/lib
vendor/lib64
vendor/lib64/egl
vendor/lib64/hw
vendor/lib64/soundfx
vendor/lib/egl
vendor/lib/hw
vendor/lib/mediadrm
vendor/lib/qcdrm/playready/lib
vendor/lib/qcdrm/playready/lib/drm
vendor/lib/qcdrm/playready/lib/mediadrm
vendor/radio/qcril_database
vendor/lib/rfsa/adsp
vendor/lib/soundfx
xbin
"

for i in ${list}
do
  mkdir -p ${PREBUILT_PATH}${i}
done

bin_list="
adsprpcd                 
ATFWD-daemon             
athdiag                  
btconfig                 
bt_logger                
btnvtool                 
cnd                      
cnss-daemon              
cnss_diag                
diag_callback_sample     
diag_dci_sample          
diag_klog                
diag_mdlog               
diag_socket_log          
diag_uart_log            
dpmd                     
DR_AP_Service            
dun-server               
energy-awareness         
fmconfig                 
fmfactorytest            
fmfactorytestserver      
fm_qsoc_patches          
ftmdaemon                
garden_app               
gpsone_daemon            
gptest                   
hal_proxy_daemon         
hci_qcomm_init           
hvdcp_opti               
imscmservice             
imsdatadaemon            
imsqmidaemon             
ims_rtp_daemon           
iop                      
ipacm-diag               
irisdaemon               
irsc_util                
KmInstallKeybox          
loc_launcher             
lowi-server              
mm-audio-ftm             
mmi                      
mmi_agent32              
mmi_agent64              
mmi_debug                
mmi_diag                 
mm-qcamera-app           
mm-qcamera-daemon        
mm-vidc-omx-test         
msm_irqbalance           
myftm                    
netmgrd                  
nl_listener              
pktlogconf               
PktRspTest               
pm-proxy                 
pm-service               
port-bridge              
ppd                      
qmi_simple_ril_test      
qseecomd                 
qseecom_sample_client    
qvop-daemon              
radish                   
rmt_storage              
secure_ui_sample_client  
seempd                   
sensors.qcom             
sns_ar_testapp           
sns_cm_conc_test         
sns_cm_test              
sns_daf_test             
sns_dsps_tc0001          
sns_hal_batch            
sns_oem_test             
sns_regedit_ssi          
soter_client             
spdaemon                 
ssr_diag                 
ssr_setup                
StoreKeybox              
subsystem_ramdump        
test_bet_8998            
test_diag                
test_module_pproc        
tftp_server              
time_daemon              
tloc_daemon              
vendor_cmd_tool          
wcnss_filter             
wdsdaemon                
wfdservice               
WifiLogger_app           
xtwifi-client            
xtwifi-inet-agent        
yuvtool    
fingerprintd              
"

for i in ${bin_list}
do
  adb pull /system/bin/${i} ${PREBUILT_PATH}bin/${i}
done

cd ${PREBUILT_PATH}bin
chmod 775 *
cd -

etc_list="
acdbdata/adsp_avs_config.acdb                               
acdbdata/MTP/MTP_Bluetooth_cal.acdb                         
acdbdata/MTP/MTP_General_cal.acdb                           
acdbdata/MTP/MTP_Global_cal.acdb                            
acdbdata/MTP/MTP_Handset_cal.acdb                           
acdbdata/MTP/MTP_Hdmi_cal.acdb                              
acdbdata/MTP/MTP_Headset_cal.acdb                           
acdbdata/MTP/MTP_Speaker_cal.acdb                           
acdbdata/MTP/MTP_workspaceFile.qwsp                         
apns-conf.xml                                               
cacert_location.pem                                         
calib.cfg                                                   
camera/camera_config.xml                                    
camera/imx350_chromatix.xml                                 
camera/imx371_chromatix.xml                                 
camera/imx376k_chromatix.xml                                
camera/imx398_chromatix.xml                                 
cdma_call_conf.xml                                          
cne/andsfCne.xml                                            
cne/SwimConfig.xml                                          
cne/wqeclient/ATT/ATT_profile1.xml                          
cne/wqeclient/ATT/ATT_profile2.xml                          
cne/wqeclient/ATT/ATT_profile3.xml                          
cne/wqeclient/ATT/ATT_profile4.xml                          
cne/wqeclient/ROW/ROW_profile1.xml                          
cne/wqeclient/ROW/ROW_profile2.xml                          
cne/wqeclient/ROW/ROW_profile3.xml                          
cne/wqeclient/ROW/ROW_profile4.xml                          
cne/wqeclient/ROW/ROW_profile5.xml                          
cne/wqeclient/VZW/VZW_profile1.xml                          
cne/wqeclient/VZW/VZW_profile2.xml                          
cne/wqeclient/VZW/VZW_profile3.xml                          
cne/wqeclient/VZW/VZW_profile4.xml                          
cne/wqeclient/VZW/VZW_profile5.xml                          
cne/wqeclient/VZW/VZW_profile6.xml
dpm/dpm.conf                                                
dpm/nsrm/NsrmConfiguration.xml                              
drc/drc_cfg_5.1.txt                                         
drc/drc_cfg_AZ.txt                                          
firmware/a225p5_pm4.fw                                      
firmware/a225_pfp.fw                                        
firmware/a225_pm4.fw                                        
firmware/a300_pfp.fw                                        
firmware/a300_pm4.fw                                        
firmware/a330_pfp.fw                                        
firmware/a330_pm4.fw                                        
firmware/a420_pfp.fw                                        
firmware/a420_pm4.fw                                        
firmware/a530_gpmu.fw2                                      
firmware/a530_pfp.fw                                        
firmware/a530_pm4.fw                                        
firmware/a530v1_pfp.fw                                      
firmware/a530v1_pm4.fw                                      
firmware/a530v2_seq.fw2                                     
firmware/a530v3_gpmu.fw2                                    
firmware/a530v3_seq.fw2                                     
firmware/a530_zap.b00                                       
firmware/a530_zap.b01                                       
firmware/a530_zap.b02                                       
firmware/a530_zap.elf                                       
firmware/a530_zap.mdt                                       
firmware/a540_gpmu.fw2                                      
firmware/a540_zap.b00                                       
firmware/a540_zap.b01                                       
firmware/a540_zap.b02                                       
firmware/a540_zap.elf                                       
firmware/a540_zap.mdt                                       
firmware/cpp_firmware_v1_10_0.fw                            
firmware/cpp_firmware_v1_1_1.fw                             
firmware/cpp_firmware_v1_12_0.fw                            
firmware/cpp_firmware_v1_1_6.fw                             
firmware/cpp_firmware_v1_2_0.fw                             
firmware/cpp_firmware_v1_4_0.fw                             
firmware/cpp_firmware_v1_5_0.fw                             
firmware/cpp_firmware_v1_5_2.fw                             
firmware/cpp_firmware_v1_6_0.fw                             
firmware/cpp_firmware_v1_8_0.fw                             
firmware/hbtp/hbtpcfg2.dat                                  
firmware/hbtp/hbtpcfg.dat                                   
firmware/hbtp/qtc800h.bin                                   
firmware/hbtp/qtc800s_dsp.bin                               
firmware/ipa_fws.b00                                        
firmware/ipa_fws.b01                                        
firmware/ipa_fws.b02                                        
firmware/ipa_fws.b03                                        
firmware/ipa_fws.b04                                        
firmware/ipa_fws.mdt                                        
firmware/leia_pfp_470.fw                                    
firmware/leia_pm4_470.fw                                    
firmware/nvm_tlv_1.3.bin                                    
firmware/nvm_tlv_2.1.bin                                    
firmware/nvm_tlv_3.0.bin                                    
firmware/nvm_tlv_3.2.bin                                    
firmware/nvm_tlv.bin                                        
firmware/rampatch_tlv_1.3.tlv                               
firmware/rampatch_tlv_2.1.tlv                               
firmware/rampatch_tlv_3.0.tlv                               
firmware/rampatch_tlv_3.2.tlv                               
firmware/rampatch_tlv.img   
ftm_test_config                                             
ftm_test_config_msm8998-tasha-snd-card                      
mmi/fail.png                                                
mmi/fonts.ttf                                               
mmi/layout/footer_fail.xml                                  
mmi/layout/footer.xml                                       
mmi/layout/header.xml                                       
mmi/layout/layout_battery.xml                               
mmi/layout/layout_bluetooth.xml                             
mmi/layout/layout_button_backlight.xml                      
mmi/layout/layout_camera_back.xml                           
mmi/layout/layout_camera_front.xml                          
mmi/layout/layout_cb.xml                                    
mmi/layout/layout_common.xml                                
mmi/layout/layout_confirm.xml                               
mmi/layout/layout_cpu.xml                                   
mmi/layout/layout_emmc.xml                                  
mmi/layout/layout_feedback.xml                              
mmi/layout/layout_fingerprint.xml                           
mmi/layout/layout_flashlight.xml                            
mmi/layout/layout_fm.xml                                    
mmi/layout/layout_gps.xml                                   
mmi/layout/layout_gsensor.xml                               
mmi/layout/layout_gyroscope.xml                             
mmi/layout/layout_handset.xml                               
mmi/layout/layout_headset_key.xml                           
mmi/layout/layout_headset.xml                               
mmi/layout/layout_hsensor.xml                               
mmi/layout/layout_indicator.xml                             
mmi/layout/layout_keypad.xml                                
mmi/layout/layout_key.xml                                   
mmi/layout/layout_lcd_backlight.xml                         
mmi/layout/layout_lcd.xml                                   
mmi/layout/layout_led_blue.xml                              
mmi/layout/layout_led_green.xml                             
mmi/layout/layout_led_red.xml                               
mmi/layout/layout_loudspeaker.xml                           
mmi/layout/layout_lsensor.xml                               
mmi/layout/layout_memory.xml                                
mmi/layout/layout_msensor.xml                               
mmi/layout/layout_nfc.xml                                   
mmi/layout/layout_pcba.xml                                  
mmi/layout/layout_power.xml                                 
mmi/layout/layout_primary_mic.xml                           
mmi/layout/layout_psensor.xml                               
mmi/layout/layout_reboot.xml                                
mmi/layout/layout_report.xml                                
mmi/layout/layout_sdcard.xml                                
mmi/layout/layout_simcard1.xml                              
mmi/layout/layout_simcard2.xml                              
mmi/layout/layout_system_info.xml                           
mmi/layout/layout_telephone.xml                             
mmi/layout/layout_touch.xml                                 
mmi/layout/layout_vibrator.xml                              
mmi/layout/layout_wifi.xml                                  
mmi/layout/main_wear.xml                                    
mmi/layout/main.xml                                         
mmi/mmi.xml                                                 
mmi/pagedown.png                                            
mmi/pageup.png                                              
mmi/pass.png                                                
mmi/path_config.xml                                         
mmi/poweroff.png                                            
mmi/qualsound.wav                                           
mmi/reboot.png                                              
mmi/report.png                                              
mmi/reset.png                                               
mmi/runall.png                                              
mmi/strings.xml                                             
mmi/strings-zh-rCN.xml                                      
permissions/audiosphere.xml                                 
permissions/btmultisim.xml                                  
permissions/cneapiclient.xml                                
permissions/com.qti.dpmframework.xml                        
permissions/com.qti.location.sdk.xml                        
permissions/com.qti.snapdragon.sdk.display.xml              
permissions/com.qualcomm.location.vzw_library.xml           
permissions/com.qualcomm.location.xml                      
permissions/com.quicinc.cne.xml 
permissions/ConnectivityExt.xml                             
permissions/dpmapi.xml                                      
permissions/embms.xml                                       
permissions/imscm.xml                                       
permissions/izat.xt.srv.xml                                 
permissions/lpa.xml                                         
permissions/qcnvitems.xml                                   
permissions/qcrilhook.xml                                   
permissions/qti_permissions.xml                             
permissions/qti-vzw-ims-internal.xml                        
permissions/telephonyservice.xml                            
qdcm_calib_data_samsung_s6e3fa5_1080p_cmd_mode_dsi_panel.xml
qdcm_calib_data_samsung_s6e3fa6_1080p_cmd_mode_dsi_panel.xml
qdcm_calib_data_samsung_s6e3fc1_cmd_mode_dsi_panel.xml      
qvop/antispoofing.bin                                       
qvop/cmudict.bin                                            
qvop/noisesample.bin                                        
qvop/poc_64_hmm.gmm                                         
sensors/sensor_def_qcomdev.conf                             
spn-conf.xml                                                
surround_sound_3mic/surround_sound_rec_5.1.cfg              
surround_sound_3mic/surround_sound_rec_AZ.cfg               
thermal-engine.conf                                         
wfdconfigsink.xml                                           
wfdconfig.xml                                               
xtra_root_cert.pem   
data/dsi_config.xml
data/netmgr_config.xml
permissions/android.hardware.fingerprint.xml
permissions/com.fingerprints.extension.xml 

"

for i in ${etc_list}
do
  adb pull /system/etc/${i} ${PREBUILT_PATH}etc/${i}
done

lib_list="
hw/camera.msm8998.so           
hw/gps.default.so              
hw/lights.msm8998.so           
libgnsspps.so                  
libgps.utils.so                
libiriscamera.so               
libirisdev.so                  
libiris_oem_default.so         
libloc_api_v02.so              
libloc_core.so                 
libloc_ds_api.so               
libloc_eng.so                  
libloc_pla.so                  
libloc_stub.so                 
libminui.so                    
libmmcamera_interface.so       
libmmjpeg_interface.so         
libmmlib2d_interface.so        
libmm-qcamera.so               
libOmxVpp.so                   
libparam.so                    
libqomx_core.so                
libstagefright_soft_flacdec.so 
libvpplibrary.so               
hw/fingerprint.msm8998.so
hw/fingerprint.msm8998.gf.so
libgoodixfingerprintd_binder.so
libgf_hal.so
libgf_ca.so
libopcamera_native_modules.so
libopposfr.so
libmms_gyro_vstab.so
libmms_hal_vstab.so
libmms_warper_vstab.so
libSensorManagerHAL.so
libmms_gyro_vstab_auth.so
lib_oneplus_facebeauty.so
lib_oneplus_watermark.so
libVDBlurlessAPI.so
libVDHDRAPI.so
lib_oneplus_md.so
"

for i in ${lib_list}
do
  adb pull /system/lib/${i} ${PREBUILT_PATH}lib/${i}
done

lib64_list="
hw/gps.default.so             
libgnsspps.so                 
libgps.utils.so               
libloc_api_v02.so             
libloc_core.so                
libloc_ds_api.so              
libloc_eng.so                 
libloc_pla.so                 
libloc_stub.so                
libminui.so                   
libOmxVpp.so                  
libparam.so                   
libstagefright_soft_flacdec.so
libvehiclenetwork-native.so   
libvpplibrary.so              
libnfc-nci.so
libnfc_nci_jni.so
libp61-jcop-kit.so
hw/nfc_nci.pn54x.default.so
hw/fingerprint.msm8998.so
hw/fingerprint.msm8998.gf.so
libgoodixfingerprintd_binder.so
libgf_hal.so
libgf_ca.so
"
for i in ${lib64_list}
do
  adb pull /system/lib64/${i} ${PREBUILT_PATH}lib64/${i}
done

usr_list="
"

for i in ${usr_list}
do
  adb pull /system/usr/${i} ${PREBUILT_PATH}usr/${i}
done

vendor_list="
bin/audioflacapp         
bin/chamomile_provision  
bin/esepmdaemon          
bin/hbtp_daemon          
bin/hdcp1prov            
bin/mdtpd                
bin/mm-pp-dpps           
bin/mm-qjpeg-dec-test    
bin/mm-qjpeg-enc-test    
bin/mm-qomx-idec-test    
bin/mm-qomx-ienc-test    
bin/pd-mapper            
bin/perfd                
bin/qjpeg-dma-test       
bin/qseeproxydaemon      
bin/qseeproxysampledaemon
bin/qti                  
bin/qvrservice           
bin/qvrservicetest       
bin/qvrservicetest64     
bin/RIDLClient.exe       
bin/seemp_healthd        
bin/slim_daemon          
bin/smcinvoked           
bin/thermal-engine     
etc/apdr.conf                                                       
etc/flp.conf                                                        
etc/izat.conf                                                       
etc/lowi.conf                                                       
etc/public.libraries.txt                                            
etc/qvr/qvrservice_6dof_config.xml                                  
etc/qvr/qvrservice_config.txt                                       
etc/RIDL/GoldenLogmask.dmc                                          
etc/RIDL/OTA-Logs.dmc                                               
etc/RIDL/qdss.cfg                                                   
etc/RIDL/RIDL.db                                                    
etc/sap.conf                                                        
etc/scve/facereco/gModel.dat                                        
etc/scve/textreco/chardecoder/character.cost                        
etc/scve/textreco/chardecoder/CharType.dat                          
etc/scve/textreco/chardecoder/ChinesePunctuation.rst              
etc/scve/textreco/chardecoder/cnn_small5_synthrev_sw_sampled2_bin                                                      
etc/scve/textreco/chardecoder/_conf_eng_num_sym_font40_4transd_zscore_morph_.trn2876.trn                             
etc/scve/textreco/chardecoder/_conf_eng_num_sym_font40_conc2_meshrn__de__1_1__zscore_morph.trn10158.trn              
etc/scve/textreco/chardecoder/_conf_eng_num_sym_font40_rbp_data5100_patch500_5x5_24x24_dim727.trn31585.trn           
etc/scve/textreco/chardecoder/_eng_font40_4transmeshrnorm6x6_leaflda85_ligature_ext14_c70_sp1lI_newxml3.trn31299.trn 
etc/scve/textreco/chardecoder/GLVQDecoder_fixed.ohie                                                                 
etc/scve/textreco/chardecoder/glvq_kor_2197classes_576_100dim_i42_centroidNorm.dat                                   
etc/scve/textreco/chardecoder/glvq_kor_consonant_19classes_64_16dim_i0_linearNorm.dat                                
etc/scve/textreco/chardecoder/hGLVQ_kor_RLF80_float.hie                                                              
etc/scve/textreco/chardecoder/LDA_kor_2197classes_576dim_centroidNorm.dat                                            
etc/scve/textreco/chardecoder/LDA_kor_consonant_19classes_64dim_linearNorm.dat                                       
etc/scve/textreco/chardecoder/_numpunc_font40_4transmeshrnorm_leafnum1.trn9614.trn                                   
etc/scve/textreco/chardecoder/_numpunc_font40_conc2_DEFn__BGTouchy6x6n__1_1__morph.trn32025.trn                      
etc/scve/textreco/chardecoder/_numpunc_parteng_font40_4transmeshr_morph.trn400.trn                                   
etc/scve/textreco/chardecoder/punRangeData.rst                                                                       
etc/scve/textreco/textdetector/dcnConfigForEngCNN.txt                                                                
etc/scve/textreco/textdetector/dcnConfigForMultiCNN.txt                                                              
etc/scve/textreco/textdetector/forestData.bin                                                                        
etc/scve/textreco/textdetector/nontextremoval_eng.model                                                              
etc/scve/textreco/textdetector/nontextremoval_multilang.model                                                        
etc/scve/textreco/worddecoder/chinese_address_20150304.bin                                                           
etc/scve/textreco/worddecoder/chinese.lm                                                                             
etc/scve/textreco/worddecoder/english_address_20150213.bin                                                           
etc/scve/textreco/worddecoder/english_dictionary_20150213.bin                                                        
etc/scve/textreco/worddecoder/korean_address_20150129.bin                                                            
etc/scve/textreco/worddecoder/korean_dictionary_20150414.bin                                                         
etc/scve/textreco/worddecoder/korean.lm                                                                              
etc/xtwifi.conf     
lib/egl/eglSubDriverAndroid.so                                   
lib/egl/libEGL_adreno.so                                         
lib/egl/libGLESv1_CM_adreno.so                                   
lib/egl/libGLESv2_adreno.so                                      
lib/egl/libq3dtools_adreno.so                                    
lib/egl/libq3dtools_esx.so                                       
lib/egl/libQTapGLES.so                                           
lib/hw/activity_recognition.msm8998.so                           
lib/hw/flp.default.so                                            
lib/libacdb-fts.so                                               
lib/libacdbloader.so                                             
lib/libacdbmapper.so                                             
lib/libacdbrtac.so                                               
lib/libactuator_lc898217xc_imx350.so                             
lib/libactuator_lc898217xc_imx376k.so                            
lib/libactuator_lc898217xc_imx398.so                             
lib/libadiertac.so                                               
lib/libadm.so                                                    
lib/libadreno_utils.so                                           
lib/libadsp_default_listener.so                                  
lib/libadsp_hvx_callback_skel.so                                 
lib/libadsp_hvx_stub.so                                          
lib/libadsprpc.so                                                
lib/libAlacSwDec.so                                              
lib/libalarmservice_jni.so                                       
lib/libApeSwDec.so                                               
lib/libarcsoft_dualcam_refocus.so                                
lib/libAR_jni.so                                                 
lib/libaudcal.so                                                 
lib/libaudioalsa.so                                              
lib/libavenhancements.so                                         
lib/libbase64.so                                                 
lib/libbccQTI.so                                                 
lib/libblurbuster.so                                             
lib/libbt-logClient.so                                           
lib/libbtnv.so                                                   
lib/libbt-vendor.so                                              
lib/libC2D2.so                                                   
lib/libc2d30-a3xx.so                                             
lib/libc2d30-a4xx.so                                             
lib/libc2d30-a5xx.so                                             
lib/libc2d30_bltlib.so                                           
lib/libcamera_bokeh_wrapper.so                                   
lib/libcamera_cp_bokeh.so                                        
lib/libcamera_cp_wrapper.so                                      
lib/libcamera_oneplus_bokeh_wrapper.so                           
lib/libCB.so                                                     
lib/libcdsprpc.so                                                
lib/libChamomilePA.so                                            
lib/libchromaflash.so                                            
lib/libchromatix_imx350_3a_1536x866_30fps_video.so               
lib/libchromatix_imx350_3a_2304x1300_30fps_preview.so            
lib/libchromatix_imx350_3a_2304x1300_30fps_video.so              
lib/libchromatix_imx350_3a_2592x1940_24fps_preview_bokeh.so      
lib/libchromatix_imx350_3a_4160x3120_30fps_preview_bokeh.so      
lib/libchromatix_imx350_3a_4608x3456_27fps_preview.so            
lib/libchromatix_imx350_3a_5184x3880_30fps_preview.so            
lib/libchromatix_imx350_common.so                                
lib/libchromatix_imx350_cpp_1536x866_30fps_video.so              
lib/libchromatix_imx350_cpp_2304x1300_30fps_video.so             
lib/libchromatix_imx350_cpp_4160x3120_30fps_preview_bokeh.so     
lib/libchromatix_imx350_cpp_4160x3120_30fps_snapshot_bokeh.so    
lib/libchromatix_imx350_cpp_4608x3456_27fps_preview.so           
lib/libchromatix_imx350_cpp_4608x3456_27fps_snapshot.so          
lib/libchromatix_imx350_cpp_5184x3880_30fps_preview.so           
lib/libchromatix_imx350_cpp_5184x3880_30fps_snapshot.so          
lib/libchromatix_imx350_isp_1536x866_30fps_video.so              
lib/libchromatix_imx350_isp_2304x1300_30fps_video.so             
lib/libchromatix_imx350_isp_4160x3120_30fps_snapshot_bokeh.so    
lib/libchromatix_imx350_isp_4608x3456_27fps_snapshot.so          
lib/libchromatix_imx350_isp_5184x3880_30fps_snapshot.so          
lib/libchromatix_imx350_postproc.so                              
lib/libchromatix_imx371_3a_2304x1728_30fps_auto_hdr.so           
lib/libchromatix_imx371_3a_2304x1728_30fps_hdr.so                
lib/libchromatix_imx371_3a_2304x1728_30fps_preview.so            
lib/libchromatix_imx371_3a_2304x1728_30fps_video.so              
lib/libchromatix_imx371_3a_4656x3456_30fps_preview.so            
lib/libchromatix_imx371_3a_640x480_120fps_video.so               
lib/libchromatix_imx371_common.so                                
lib/libchromatix_imx371_cpp_2304x1728_30fps_flash.so             
lib/libchromatix_imx371_cpp_2304x1728_30fps_hdr.so               
lib/libchromatix_imx371_cpp_2304x1728_30fps_liveshot.so          
lib/libchromatix_imx371_cpp_2304x1728_30fps_preview.so           
lib/libchromatix_imx371_cpp_2304x1728_30fps_snapshot.so          
lib/libchromatix_imx371_cpp_2304x1728_30fps_video.so             
lib/libchromatix_imx371_cpp_4656x3456_30fps_snapshot.so          
lib/libchromatix_imx371_cpp_640x480_120fps_video.so              
lib/libchromatix_imx371_isp_2304x1728_30fps_snapshot.so          
lib/libchromatix_imx371_isp_2304x1728_30fps_video.so             
lib/libchromatix_imx371_isp_4656x3456_30fps_snapshot.so          
lib/libchromatix_imx371_isp_640x480_120fps_video.so              
lib/libchromatix_imx371_postproc.so                              
lib/libchromatix_imx376k_3a_1840x1380_30fps_preview_bokeh.so     
lib/libchromatix_imx376k_3a_2592x1458_120fps_video.so            
lib/libchromatix_imx376k_3a_2592x1458_60fps_video.so             
lib/libchromatix_imx376k_3a_2592x1940_30fps_preview_bokeh.so     
lib/libchromatix_imx376k_3a_2592x1940_30fps_preview.so           
lib/libchromatix_imx376k_common.so                               
lib/libchromatix_imx376k_cpp_2592x1458_120fps_video.so           
lib/libchromatix_imx376k_cpp_2592x1458_60fps_video.so            
lib/libchromatix_imx376k_cpp_2592x1940_24fps_preview_bokeh.so    
lib/libchromatix_imx376k_cpp_2592x1940_24fps_snapshot_bokeh.so   
lib/libchromatix_imx376k_cpp_2592x1940_30fps_preview.so          
lib/libchromatix_imx376k_cpp_2592x1940_30fps_snapshot.so         
lib/libchromatix_imx376k_isp_2592x1458_120fps_video.so           
lib/libchromatix_imx376k_isp_2592x1458_60fps_video.so            
lib/libchromatix_imx376k_isp_2592x1940_24fps_snapshot_bokeh.so   
lib/libchromatix_imx376k_isp_2592x1940_30fps_snapshot.so         
lib/libchromatix_imx376k_postproc.so                             
lib/libchromatix_imx398_3a_1476x834_120fps_video.so              
lib/libchromatix_imx398_3a_2328x1304_60fps_video.so              
lib/libchromatix_imx398_3a_3264x2448_30fps_preview_bokeh.so      
lib/libchromatix_imx398_3a_4656x2608_30fps_preview.so            
lib/libchromatix_imx398_3a_4656x2608_30fps_video_4k.so           
lib/libchromatix_imx398_3a_4656x2608_30fps_video.so              
lib/libchromatix_imx398_3a_4656x3496_30fps_preview.so            
lib/libchromatix_imx398_3a_hq.so                                 
lib/libchromatix_imx398_3a_manual.so                             
lib/libchromatix_imx398_3a_panorama.so                           
lib/libchromatix_imx398_common.so                                
lib/libchromatix_imx398_cpp_1476x834_120fps_video.so             
lib/libchromatix_imx398_cpp_2328x1304_60fps_video.so             
lib/libchromatix_imx398_cpp_3264x2448_30fps_preview_bokeh.so     
lib/libchromatix_imx398_cpp_3264x2448_30fps_snapshot_bokeh.so    
lib/libchromatix_imx398_cpp_4656x2608_30fps_preview.so           
lib/libchromatix_imx398_cpp_4656x2608_30fps_video_4k.so          
lib/libchromatix_imx398_cpp_4656x2608_30fps_video.so             
lib/libchromatix_imx398_cpp_4656x3496_30fps_preview.so           
lib/libchromatix_imx398_cpp_4656x3496_30fps_snapshot.so          
lib/libchromatix_imx398_cpp_snapshot_flash.so                    
lib/libchromatix_imx398_cpp_snapshot_hdr.so                      
lib/libchromatix_imx398_cpp_snapshot_manual.so                   
lib/libchromatix_imx398_cpp_snapshot_motion.so                   
lib/libchromatix_imx398_cpp_snapshot_nomultiframe.so             
lib/libchromatix_imx398_cpp_snapshot_zoom.so                     
lib/libchromatix_imx398_isp_1476x834_120fps_video.so             
lib/libchromatix_imx398_isp_2328x1304_60fps_video.so             
lib/libchromatix_imx398_isp_3264x2448_30fps_snapshot_bokeh.so    
lib/libchromatix_imx398_isp_4656x2608_30fps_video.so             
lib/libchromatix_imx398_isp_4656x3496_30fps_preview.so           
lib/libchromatix_imx398_isp_4656x3496_30fps_snapshot.so          
lib/libchromatix_imx398_isp_manual.so                            
lib/libchromatix_imx398_isp_panorama.so                          
lib/libchromatix_imx398_postproc.so                              
lib/libcneapiclient.so                                           
lib/libcneqmiutils.so                                            
lib/libcne.so                                                    
lib/libconfigdb.so                                               
lib/libconnctrl.so                                               
lib/libcppf.so                                                   
lib/libcvface_api.so                                             
lib/libdataitems.so                                              
lib/libdczoom.so                                                 
lib/libDevHealth.so                                              
lib/libdiag.so                                                   
lib/libdisp-aba.so                                               
lib/lib-dplmedia.so                                              
lib/libdpmctmgr.so                                               
lib/libdpmfdmgr.so                                               
lib/libdpmframework.so                                           
lib/libdpmnsrm.so                                                
lib/libdpmtcm.so                                                 
lib/libdrc.so                                                    
lib/libdrmfs.so                                                  
lib/libdrmtime.so                                                
lib/libdrplugin_client.so                                        
lib/lib_drplugin_server.so                                       
lib/libDRPlugin.so                                               
lib/libdsd2pcm.so                                                
lib/libdsi_netctrl.so                                            
lib/libdsutils.so                                                
lib/libdualcameraddm.so                                          
lib/libedge_smooth_hvx_stub.so                                   
lib/libedgesmooth.so                                             
lib/libEGL_adreno.so                                             
lib/libesepm.so                                                  
lib/libevent_observer.so                                         
lib/libExtendedExtractor.so                                      
lib/libfastcrc.so                                                
lib/libfastcvadsp_stub.so                                        
lib/libfastcvopt.so                                              
lib/libfastrpc_utf_stub.so                                       
lib/libFidoCryptoJNI.so                                          
lib/libFidoCrypto.so                                             
lib/libFIDOKeyProvisioning.so                                    
lib/libFidoSuiJNI.so                                             
lib/libFileMux.so                                                
lib/libfiltergenerator.so                                        
lib/libFlacSwDec.so                                              
lib/libflash_pmic.so                                             
lib/libflp.so                                                    
lib/libgcs-calwrapper.so                                         
lib/libgcs-ipc.so                                                
lib/libgcs-osal.so                                               
lib/libgcs.so                                                    
lib/libgdtap.so                                                  
lib/libgeofence.so                                               
lib/libGLESv2_adreno.so                                          
lib/libGPreqcancel.so                                            
lib/libGPreqcancel_svc.so                                        
lib/libGPTEE.so                                                  
lib/libgsl.so                                                    
lib/libhbtpclient.so                                             
lib/libhbtpdsp.so                                                
lib/libhbtpfrmwk.so                                              
lib/libhbtpitsjni.so                                             
lib/libhbtpjni.so                                                
lib/libhdcp1prov.so                                              
lib/libhdr_tm.so                                                 
lib/libHealthAuthClient.so                                       
lib/libHealthAuthJNI.so                                          
lib/libhwdaphal.so                                               
lib/libI420colorconvert.so                                       
lib/libimscamera_jni.so                                          
lib/lib-imscamera.so                                             
lib/lib-imsdpl.so                                                
lib/libimsmedia_jni.so                                           
lib/lib-imsqimf.so                                               
lib/lib-imsrcscmclient.so                                        
lib/lib-ims-rcscmjni.so                                          
lib/lib-imsrcscmservice.so                                       
lib/lib-imsrcscm.so                                              
lib/lib-imsrcs.so                                                
lib/lib-imsSDP.so                                                
lib/lib-imss.so                                                  
lib/lib-imsvt.so                                                 
lib/lib-imsxml.so                                                
lib/libizat_client_api.so                                        
lib/libizat_core.so                                              
lib/libjni_blurbuster.so                                         
lib/libjni_chromaflash.so                                        
lib/libjni_dualcamera.so                                         
lib/libjni_filtergenerator.so                                    
lib/libjni_makeupV2.so                                           
lib/libjni_optizoom.so                                           
lib/libjni_panorama.so                                           
lib/libjni_sharpshooter.so                                       
lib/libjni_stillmore.so                                          
lib/libjni_trackingfocus.so                                      
lib/libjni_ubifocus.so                                           
lib/libjpegdhw.so                                                
lib/libjpegdmahw.so                                              
lib/libjpegehw.so                                                
lib/libkeymasterprovision.so                                     
lib/liblbs_core.so                                               
lib/liblistenjni.so                                              
lib/liblistensoundmodel2.so                                      
lib/libllvm-glnext.so                                            
lib/libllvm-qcom.so                                              
lib/libllvm-qgl.so                                               
lib/liblocationservice_glue.so                                   
lib/liblocationservice.so                                        
lib/libloc_externalDr.so                                         
lib/libloc_ext.so                                                
lib/liblowi_client.so                                            
lib/liblowi_wifihal_nl.so                                        
lib/liblowi_wifihal.so                                           
lib/liblqe.so                                                    
lib/libmdmdetect.so                                              
lib/libmdsprpc.so                                                
lib/libmdtp_crypto.so                                            
lib/libmdtpdemojni.so                                            
lib/libmdtp.so                                                   
lib/libmiracast.so                                               
lib/libmmcamera2_c2d_module.so                                   
lib/libmmcamera2_cpp_module.so                                   
lib/libmmcamera2_frame_algorithm.so                              
lib/libmmcamera2_iface_modules.so                                
lib/libmmcamera2_imglib_modules.so                               
lib/libmmcamera2_isp_modules.so                                  
lib/libmmcamera2_is.so                                           
lib/libmmcamera2_mct_shimlayer.so                                
lib/libmmcamera2_mct.so                                          
lib/libmmcamera2_pp_buf_mgr.so                                   
lib/libmmcamera2_pproc_modules.so                                
lib/libmmcamera2_q3a_core.so                                     
lib/libmmcamera2_sensor_modules.so                               
lib/libmmcamera2_stats_algorithm.so                              
lib/libmmcamera2_stats_lib.so                                    
lib/libmmcamera2_stats_modules.so                                
lib/libmmcamera_chromaflash_lib.so                               
lib/libmmcamera_dbg.so                                           
lib/libmmcamera_dummyalgo.so                                     
lib/libmmcamera_edgesmooth_lib.so                                
lib/libmmcamera_eebinparse.so                                    
lib/libmmcamera_eeprom_util.so                                   
lib/libmmcamera_eztune_module.so                                 
lib/libmmcamera_facedetection_lib.so                             
lib/libmmcamera_faceproc2.so                                     
lib/libmmcamera_faceproc.so                                      
lib/libmmcamera_hdr_gb_lib.so                                    
lib/libmmcamera_hvx_add_constant.so                              
lib/libmmcamera_hvx_grid_sum.so                                  
lib/libmmcamera_imglib_faceproc_adspstub2.so                     
lib/libmmcamera_imglib_faceproc_adspstub.so                      
lib/libmmcamera_imglib.so                                        
lib/libmmcamera_imx350_gt24c64ass_eeprom.so                      
lib/libmmcamera_imx350.so                                        
lib/libmmcamera_imx371.so                                        
lib/libmmcamera_imx376k_gt24c64_eeprom.so                        
lib/libmmcamera_imx376k.so                                       
lib/libmmcamera_imx398_gt24c64_eeprom.so                         
lib/libmmcamera_imx398.so                                        
lib/libmmcamera_isp_abf48.so                                     
lib/libmmcamera_isp_aec_bg_stats47.so                            
lib/libmmcamera_isp_bf_stats47.so                                
lib/libmmcamera_isp_bg_stats46.so                                
lib/libmmcamera_isp_bhist_stats44.so                             
lib/libmmcamera_isp_black_level48.so                             
lib/libmmcamera_isp_bpc48.so                                     
lib/libmmcamera_isp_cac47.so                                     
lib/libmmcamera_isp_chroma_enhan40.so                            
lib/libmmcamera_isp_chroma_suppress40.so                         
lib/libmmcamera_isp_clamp_encoder40.so                           
lib/libmmcamera_isp_clamp_video40.so                             
lib/libmmcamera_isp_clamp_viewfinder40.so                        
lib/libmmcamera_isp_color_correct46.so                           
lib/libmmcamera_isp_color_xform_encoder46.so                     
lib/libmmcamera_isp_color_xform_video46.so                       
lib/libmmcamera_isp_color_xform_viewfinder46.so                  
lib/libmmcamera_isp_cs_stats46.so                                
lib/libmmcamera_isp_demosaic48.so                                
lib/libmmcamera_isp_demux48.so                                   
lib/libmmcamera_isp_fovcrop_encoder46.so                         
lib/libmmcamera_isp_fovcrop_video46.so                           
lib/libmmcamera_isp_fovcrop_viewfinder46.so                      
lib/libmmcamera_isp_gamma44.so                                   
lib/libmmcamera_isp_gic48.so                                     
lib/libmmcamera_isp_gtm46.so                                     
lib/libmmcamera_isp_hdr48.so                                     
lib/libmmcamera_isp_hdr_be_stats46.so                            
lib/libmmcamera_isp_hdr_bhist_stats44.so                         
lib/libmmcamera_isp_ihist_stats46.so                             
lib/libmmcamera_isp_linearization40.so                           
lib/libmmcamera_isp_ltm47.so                                     
lib/libmmcamera_isp_luma_adaptation40.so                         
lib/libmmcamera_isp_mce40.so                                     
lib/libmmcamera_isp_mesh_rolloff44.so                            
lib/libmmcamera_isp_pdaf48.so                                    
lib/libmmcamera_isp_pedestal_correct46.so                        
lib/libmmcamera_isp_rs_stats46.so                                
lib/libmmcamera_isp_scaler_encoder46.so                          
lib/libmmcamera_isp_scaler_video46.so                            
lib/libmmcamera_isp_scaler_viewfinder46.so                       
lib/libmmcamera_isp_sce40.so                                     
lib/libmmcamera_isp_snr47.so                                     
lib/libmmcamera_isp_sub_module.so                                
lib/libmmcamera_llvd.so                                          
lib/libmmcamera_optizoom_lib.so                                  
lib/libmmcamera_paaf_lib.so                                      
lib/libmmcamera_pdafcamif.so                                     
lib/libmmcamera_pdaf.so                                          
lib/libmmcamera_ppbase_module.so                                 
lib/libmmcamera_ppeiscore.so                                     
lib/libmmcamera_quadracfa.so                                     
lib/libmmcamera_s5k3p8sp_m24c64s_eeprom.so                       
lib/libmmcamera_sac_lib.so                                       
lib/libmmcamera_sat_dummy_lib.so                                 
lib/libmmcamera_sony_imx371_eeprom.so                            
lib/libmmcamera_stillmore_lib.so                                 
lib/libmmcamera_sw2d_lib.so                                      
lib/libmmcamera_thread_services.so                               
lib/libmmcamera_tintless_algo.so                                 
lib/libmmcamera_tintless_bg_pca_algo.so                          
lib/libmmcamera_trueportrait_lib.so                              
lib/libmmcamera_tuning_lookup.so                                 
lib/libmmcamera_tuning.so                                        
lib/libmm-color-convertor.so                                     
lib/libmm-disp-apis.so                                           
lib/libmm-hdcpmgr.so                                             
lib/libmmi.so                                                    
lib/libmmjpeg.so                                                 
lib/libmmosal.so                                                 
lib/libmmparser_lite.so                                          
lib/libmmparser.so                                               
lib/libmm-qdcm-diag.so                                           
lib/libmm-qdcm.so                                                
lib/libmmqjpeg_codec.so                                          
lib/libmmqjpegdma.so                                             
lib/libmmrtpdecoder.so                                           
lib/libmmrtpencoder.so                                           
lib/libmpbase.so                                                 
lib/libnative_audio_latency_jni.so                               
lib/libnetmgr.so                                                 
lib/libOmxAacDec.so                                              
lib/libOmxAlacDec.so                                             
lib/libOmxAlacDecSw.so                                           
lib/libOmxAmrwbplusDec.so                                        
lib/libOmxApeDec.so                                              
lib/libOmxApeDecSw.so                                            
lib/libOmxDsdDec.so                                              
lib/libomx-dts.so                                                
lib/libOmxEvrcDec.so                                             
lib/libOmxMux.so                                                 
lib/libOmxQcelp13Dec.so                                          
lib/libOmxVideoDSMode.so                                         
lib/libOmxWmaDec.so                                              
lib/libOpenCL.so                                                 
lib/liboptizoom.so                                               
lib/libpdmapper.so                                               
lib/libpdnotifier.so                                             
lib/libperipheral_client.so                                      
lib/libpvr.so                                                    
lib/libqcci_legacy.so                                            
lib/libqcmaputils.so                                             
lib/libqct_resampler.so                                          
lib/libqdi.so                                                    
lib/libqdp.so                                                    
lib/libqisl.so                                                   
lib/libqmi_client_helper.so                                      
lib/libqmi_client_qmux.so                                        
lib/libqmi_csi.so                                                
lib/libqmi_encdec.so                                             
lib/libqmi.so                                                    
lib/libqomx_jpegdec.so                                           
lib/libqomx_jpegenc_pipe.so                                      
lib/libqomx_jpegenc.so                                           
lib/libQSEEComAPI.so                                             
lib/libqseed3.so                                                 
lib/libqti-at.so                                                 
lib/libqtigef.so                                                 
lib/libqti-iop-client.so                                         
lib/libqti-iop.so                                                
lib/libqti-perfd-client.so                                       
lib/libqti_performance.so                                        
lib/libQtiTether.so                                              
lib/libqti-util.so                                               
lib/libqti-utils.so                                              
lib/libquipc_os_api.so                                           
lib/libqvop-service.so                                           
lib/libqvr_adsp_driver_stub.so                                   
lib/libqvrservice_client.so                                      
lib/libqvrservice.so                                             
lib/librcc.so                                                    
lib/lib-rcsimssjni.so                                            
lib/lib-rcsjni.so                                                
lib/lib_remote_simlock.so                                        
lib/libril-qc-ltedirectdisc.so                                   
lib/libril-qc-qmi-1.so                                           
lib/libril-qc-radioconfig.so                                     
lib/libril-qcril-hook-oem.so                                     
lib/librilqmiservices.so                                         
lib/librmp.so                                                    
lib/librpmb.so                                                   
lib/librs_adreno_sha1.so                                         
lib/librs_adreno.so                                              
lib/libRSDriver_adreno.so                                        
lib/lib-rtpcommon.so                                             
lib/lib-rtpcore.so                                               
lib/lib-rtpdaemoninterface.so                                    
lib/lib-rtpsl.so                                                 
lib/libSampleAuthJNI.so                                          
lib/libSampleExtAuthJNI.so                                       
lib/libscveBlobDescriptor.so                                     
lib/libscveBlobDescriptor_stub.so                                
lib/libscveCleverCapture.so                                      
lib/libscveCleverCapture_stub.so                                 
lib/libscveCommon.so                                             
lib/libscveCommon_stub.so                                        
lib/libscveFaceLandmarks.so                                      
lib/libscveFaceLandmarks_stub.so                                 
lib/libscveFaceRecognition.so                                    
lib/libscveFaceRecognition_stub.so                               
lib/libscveImageCloning.so                                       
lib/libscveImageCorrection.so                                    
lib/libscveImageRemoval.so                                       
lib/libscveMotionVector.so                                       
lib/libscveObjectMatting.so                                      
lib/libscveObjectMatting_stub.so                                 
lib/libscveObjectSegmentation.so                                 
lib/libscveObjectSegmentation_stub.so                            
lib/libscveObjectTracker.so                                      
lib/libscveObjectTracker_stub.so                                 
lib/libscvePanorama_lite.so                                      
lib/libscvePanorama.so                                           
lib/libscveTextRecoPostProcessing.so                             
lib/libscveTextReco.so                                           
lib/libscveTextReco_stub.so                                      
lib/libscveVideoSummary.so                                       
lib/libscveVideoSummary_stub.so                                  
lib/libsdm-color.so                                              
lib/libsdm-diag.so                                               
lib/libsdm-disp-apis.so                                          
lib/libsdmextension.so                                           
lib/libsd_sdk_display.so                                         
lib/libsdsprpc.so                                                
lib/libseccam.so                                                 
lib/libseccam_vendor.so                                          
lib/lib-sec-disp.so                                              
lib/libSecureExtAuthJNI.so                                       
lib/libSecureSampleAuthJNI.so                                    
lib/libSecureUILib.so                                            
lib/libsecureui.so                                               
lib/libsecureuisvc_jni.so                                        
lib/libsecureui_svcsock.so                                       
lib/libseemore.so                                                
lib/libseemp_binder.so                                           
lib/libSeemplog.so                                               
lib/libSeempMsgService.so                                        
lib/libseempnative.so                                            
lib/libsensor1.so                                                
lib/libsensor_reg.so                                             
lib/libsensor_test.so                                            
lib/libsensor_thresh.so                                          
lib/libsensor_user_cal.so                                        
lib/libsettings.so                                               
lib/libsi.so                                                     
lib/libslimclient.so                                             
lib/libsmcinvokecred.so                                          
lib/libsmemlog.so                                                
lib/libsmwrapper.so                                              
lib/libsns_low_lat_stream_stub.so                                
lib/libSonyIMX350PdafLibrary.so                                  
lib/libSonyIMX371RmscLibrary.so                                  
lib/libspcom.so                                                  
lib/libspl.so                                                    
lib/libsregex.so                                                 
lib/libssd.so                                                    
lib/libst_disp.so                                                
lib/libStDrvInt.so                                               
lib/libStereoblur.so                                             
lib/libstreamparser.so                                           
lib/libsubsystem_control.so                                      
lib/libSubSystemShutdown.so                                      
lib/libsurround_3mic_proc.so                                     
lib/libsystem_health_mon.so                                      
lib/libtar.so                                                    
lib/libthermalclient.so                                          
lib/libtime_genoff.so                                            
lib/libTimeService.so                                            
lib/libtinyxml2_1.so                                             
lib/libtrueportrait.so                                           
lib/libts_detected_face_hal.so                                   
lib/libts_detected_face_jni.so                                   
lib/libts_face_beautify_hal.so                                   
lib/libts_face_beautify_jni.so                                   
lib/libtzcom.so                                                  
lib/libtzdrmgenprov.so                                           
lib/libubifocus.so                                               
lib/libUBWC.so                                                   
lib/libulp2.so                                                   
lib/libvendorconn.so                                             
lib/libvideobokeh.so                                             
lib/libvideoutils.so                                             
lib/libvoice-svc.so                                              
lib/libvpphvx.so                                                 
lib/libvqzip.so                                                  
lib/libvr_amb_engine.so                                          
lib/libvraudio_client.so                                         
lib/libvraudio.so                                                
lib/libvr_object_engine.so                                       
lib/libvr_sam_wrapper.so                                         
lib/libwbc_jni.so                                                
lib/libwfdavenhancements.so                                      
lib/libwfdcommonutils.so                                         
lib/libwfdhdcpcp.so                                              
lib/libwfdmminterface.so                                         
lib/libwfdmmservice.so                                           
lib/libwfdmmsink.so                                              
lib/libwfdmmsrc.so                                               
lib/libwfdnative.so                                              
lib/libwfdrtsp.so                                                
lib/libwfdservice.so                                             
lib/libwfdsm.so                                                  
lib/libwfduibcinterface.so                                       
lib/libwfduibcsinkinterface.so                                   
lib/libwfduibcsink.so                                            
lib/libwfduibcsrcinterface.so                                    
lib/libwfduibcsrc.so                                             
lib/libwms.so                                                    
lib/libwqe.so                                                    
lib/libxml.so                                                    
lib/libxtadapter.so                                              
lib/libxt_native.so                                              
lib/libxtwifi_ulp_adaptor.so                                     
lib/mmi_audio.so                                                 
lib/mmi_battery.so                                               
lib/mmi_bluetooth.so                                             
lib/mmi_camera.so                                                
lib/mmi_cpu.so                                                   
lib/mmi_flashlight.so                                            
lib/mmi_fm.so                                                    
lib/mmi_gps.so                                                   
lib/mmi_headset.so                                               
lib/mmi_key.so                                                   
lib/mmi_lcd.so                                                   
lib/mmi_light.so                                                 
lib/mmi_memory.so                                                
lib/mmi_nfc.so                                                   
lib/mmi_power.so                                                 
lib/mmi_sensor.so                                                
lib/mmi_sim.so                                                   
lib/mmi_storage.so                                               
lib/mmi_sysinfo.so                                               
lib/mmi_telephone.so                                             
lib/mmi_touch.so                                                 
lib/mmi_vibrator.so                                              
lib/mmi_wifi.so                                                  
lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so           
lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so              
lib/qcdrm/playready/lib/libtzplayready_customer.so               
lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so
lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so 
lib/rfsa/adsp/capi_v2_aptX_Classic.so                            
lib/rfsa/adsp/capi_v2_aptX_HD.so                                 
lib/rfsa/adsp/libadsp_fd_skel.so                                 
lib/rfsa/adsp/libadsp_hvx_add_constant.so                        
lib/rfsa/adsp/libadsp_hvx_skel.so                                
lib/rfsa/adsp/libapps_mem_heap.so                                
lib/rfsa/adsp/libdirac17801-capiv2.so                            
lib/rfsa/adsp/libdirac_capiv2.so                                 
lib/rfsa/adsp/libdspCV_skel.so                                   
lib/rfsa/adsp/libedge_smooth_skel.so                             
lib/rfsa/adsp/libfastcvadsp_skel.so                              
lib/rfsa/adsp/libfastcvadsp.so                                   
lib/rfsa/adsp/libFastRPC_AUE_Forward_skel.so                     
lib/rfsa/adsp/libFastRPC_UTF_Forward_800h_skel.so                
lib/rfsa/adsp/libFastRPC_UTF_Forward_Qtc2_skel.so                
lib/rfsa/adsp/libFastRPC_UTF_Forward_skel.so                     
lib/rfsa/adsp/libobjectMattingApp_skel.so                        
lib/rfsa/adsp/libqvr_adsp_driver_skel.so                         
lib/rfsa/adsp/libscveBlobDescriptor_skel.so                      
lib/rfsa/adsp/libscveCleverCapture_skel.so                       
lib/rfsa/adsp/libscveFaceLandmark_skel.so                        
lib/rfsa/adsp/libscveFaceRecognition_skel.so                     
lib/rfsa/adsp/libscveObjectSegmentation_skel.so                  
lib/rfsa/adsp/libscveT2T_skel.so                                 
lib/rfsa/adsp/libscveTextReco_skel.so                            
lib/rfsa/adsp/libscveVideoSummary_skel.so                        
lib/rfsa/adsp/libvpp_frc.so                                      
lib/rfsa/adsp/libvpp_svc_skel.so                                 
lib/sensor_calibrate.so                                          
lib/sensors.ssc.so                                               
lib/soundfx/libqcbassboost.so      
lib/soundfx/libqcreverb.so                                                                
lib/soundfx/libqcvirt.so  
lib64/egl/eglSubDriverAndroid.so                  
lib64/egl/libEGL_adreno.so                        
lib64/egl/libGLESv1_CM_adreno.so                  
lib64/egl/libGLESv2_adreno.so                     
lib64/egl/libq3dtools_adreno.so                   
lib64/egl/libq3dtools_esx.so                      
lib64/egl/libQTapGLES.so                          
lib64/hw/activity_recognition.msm8998.so          
lib64/hw/flp.default.so                           
lib64/libacdb-fts.so                              
lib64/libacdbloader.so                            
lib64/libacdbmapper.so                            
lib64/libacdbrtac.so                              
lib64/libadiertac.so                              
lib64/libadreno_utils.so                          
lib64/libadsp_default_listener.so                 
lib64/libadsprpc.so                               
lib64/libAlacSwDec.so                             
lib64/libalarmservice_jni.so                      
lib64/libApeSwDec.so                              
lib64/libAR_jni.so                                
lib64/libaudcal.so                                
lib64/libaudioalsa.so                             
lib64/libavenhancements.so                        
lib64/libbccQTI.so                                
lib64/libblurbuster.so                            
lib64/libbt-logClient.so                          
lib64/libbtnv.so                                  
lib64/libbt-vendor.so                             
lib64/libC2D2.so                                  
lib64/libc2d30-a3xx.so                            
lib64/libc2d30-a4xx.so                            
lib64/libc2d30-a5xx.so                            
lib64/libc2d30_bltlib.so                          
lib64/libCB.so                                    
lib64/libcdsprpc.so                               
lib64/libChamomilePA.so                           
lib64/libchromaflash.so                           
lib64/libclearsight.so                            
lib64/libcneapiclient.so                          
lib64/libcneqmiutils.so                           
lib64/libcne.so                                   
lib64/libCommandSvc.so                            
lib64/libconfigdb.so                              
lib64/libconnctrl.so                              
lib64/libdataitems.so                             
lib64/libDevHealth.so                             
lib64/libdiag.so                                  
lib64/libdisp-aba.so                              
lib64/lib-dplmedia.so                             
lib64/libdpmctmgr.so                              
lib64/libdpmfdmgr.so                              
lib64/libdpmframework.so                          
lib64/libdpmnsrm.so                               
lib64/libdpmtcm.so                                
lib64/libdrmfs.so                                 
lib64/libdrmtime.so                               
lib64/libdrplugin_client.so                       
lib64/lib_drplugin_server.so                      
lib64/libDRPlugin.so                              
lib64/libdsi_netctrl.so                           
lib64/libdsutils.so                               
lib64/libdualcameraddm.so                         
lib64/libEGL_adreno.so                            
lib64/libesepm.so                                 
lib64/libevent_observer.so                        
lib64/libExtendedExtractor.so                     
lib64/libfastcrc.so                               
lib64/libfastcvadsp_stub.so                       
lib64/libfastcvopt.so                             
lib64/libfastrpc_utf_stub.so                      
lib64/libFidoCryptoJNI.so                         
lib64/libFidoCrypto.so                            
lib64/libFIDOKeyProvisioning.so                   
lib64/libFidoSuiJNI.so                            
lib64/libFileMux.so                               
lib64/libFlacSwDec.so                             
lib64/libflp.so                                   
lib64/libgcs-calwrapper.so                        
lib64/libgcs-ipc.so                               
lib64/libgcs-osal.so                              
lib64/libgcs.so                                   
lib64/libgdtap.so                                 
lib64/libgeofence.so                              
lib64/libGLESv2_adreno.so                         
lib64/libGPreqcancel.so                           
lib64/libGPreqcancel_svc.so                       
lib64/libGPTEE.so                                 
lib64/libgsl.so                                   
lib64/libhbtpclient.so                            
lib64/libhbtpdsp.so                               
lib64/libhbtpfrmwk.so                             
lib64/libhbtpitsjni.so                            
lib64/libhbtpjni.so                               
lib64/libhdcp1prov.so                             
lib64/libhdr_tm.so                                
lib64/libHealthAuthClient.so                      
lib64/libHealthAuthJNI.so                         
lib64/libhwdaphal.so                              
lib64/libI420colorconvert.so                      
lib64/libimscamera_jni.so                         
lib64/lib-imscamera.so                            
lib64/lib-imsdpl.so                               
lib64/libimsmedia_jni.so                          
lib64/lib-imsqimf.so                              
lib64/lib-imsrcscmclient.so                       
lib64/lib-ims-rcscmjni.so                         
lib64/lib-imsrcscmservice.so                      
lib64/lib-imsrcscm.so                             
lib64/lib-imsrcs.so                               
lib64/lib-imsSDP.so                               
lib64/lib-imss.so                                 
lib64/lib-imsvt.so                                
lib64/lib-imsxml.so                               
lib64/libizat_client_api.so                       
lib64/libizat_core.so                             
lib64/libjni_blurbuster.so                        
lib64/libjni_chromaflash.so                       
lib64/libjni_clearsight.so                        
lib64/libjni_dualcamera.so                        
lib64/libjni_makeupV2.so                          
lib64/libjni_optizoom.so                          
lib64/libjni_panorama.so                          
lib64/libjni_sharpshooter.so                      
lib64/libjni_stillmore.so                         
lib64/libjni_trackingfocus.so                     
lib64/libjni_ubifocus.so                          
lib64/libkeymasterprovision.so                    
lib64/liblbs_core.so                              
lib64/liblistenjni.so                             
lib64/liblistensoundmodel2.so                     
lib64/libllvm-glnext.so                           
lib64/libllvm-qcom.so                             
lib64/libllvm-qgl.so                              
lib64/liblocationservice_glue.so                  
lib64/liblocationservice.so                       
lib64/libloc_externalDr.so                        
lib64/libloc_ext.so                               
lib64/liblowi_client.so                           
lib64/liblowi_wifihal_nl.so                       
lib64/liblowi_wifihal.so                          
lib64/liblqe.so                                   
lib64/libmdmdetect.so                             
lib64/libmdsprpc.so                               
lib64/libmdtp_crypto.so                           
lib64/libmdtpdemojni.so                           
lib64/libmdtp.so                                  
lib64/libmiracast.so                              
lib64/libmmcamera2_frame_algorithm.so             
lib64/libmmcamera2_is.so                          
lib64/libmmcamera2_q3a_core.so                    
lib64/libmmcamera2_stats_algorithm.so             
lib64/libmmcamera2_stats_lib.so                   
lib64/libmmcamera_dbg.so                          
lib64/libmmcamera_faceproc2.so                    
lib64/libmmcamera_faceproc.so                     
lib64/libmmcamera_tintless_algo.so                
lib64/libmmcamera_tintless_bg_pca_algo.so         
lib64/libmm-color-convertor.so                    
lib64/libmm-disp-apis.so                          
lib64/libmm-hdcpmgr.so                            
lib64/libmmi.so                                   
lib64/libmmosal.so                                
lib64/libmmparser_lite.so                         
lib64/libmmparser.so                              
lib64/libmm-qdcm-diag.so                          
lib64/libmm-qdcm.so                               
lib64/libmmrtpdecoder.so                          
lib64/libmmrtpencoder.so                          
lib64/libnetmgr.so                                
lib64/libOmxAacDec.so                             
lib64/libOmxAlacDec.so                            
lib64/libOmxAlacDecSw.so                          
lib64/libOmxAmrwbplusDec.so                       
lib64/libOmxApeDec.so                             
lib64/libOmxApeDecSw.so                           
lib64/libOmxEvrcDec.so                            
lib64/libOmxMux.so                                
lib64/libOmxQcelp13Dec.so                         
lib64/libOmxWmaDec.so                             
lib64/libOpenCL.so                                
lib64/liboptizoom.so                              
lib64/libpdmapper.so                              
lib64/libpdnotifier.so                            
lib64/libperipheral_client.so                     
lib64/libpvr.so                                   
lib64/libqcci_legacy.so                           
lib64/libqcmaputils.so                            
lib64/libqdi.so                                   
lib64/libqdp.so                                   
lib64/libqisl.so                                  
lib64/libqmi_client_helper.so                     
lib64/libqmi_client_qmux.so                       
lib64/libqmi_csi.so                               
lib64/libqmi_encdec.so                            
lib64/libqmi.so                                   
lib64/libQSEEComAPI.so                            
lib64/libqseed3.so                                
lib64/libqti-at.so                                
lib64/libqtigef.so                                
lib64/libqti-iop-client.so                        
lib64/libqti-iop.so                               
lib64/libqti-perfd-client.so                      
lib64/libqti_performance.so                       
lib64/libQtiTether.so                             
lib64/libqti-util.so                              
lib64/libqti-utils.so                             
lib64/libquipc_os_api.so                          
lib64/libqvop-service.so                          
lib64/libqvrservice_client.so                     
lib64/librcc.so                                   
lib64/lib-rcsimssjni.so                           
lib64/lib-rcsjni.so                               
lib64/lib_remote_simlock.so                       
lib64/libril-qc-ltedirectdisc.so                  
lib64/libril-qc-qmi-1.so                          
lib64/libril-qc-radioconfig.so                    
lib64/libril-qcril-hook-oem.so                    
lib64/librilqmiservices.so                        
lib64/librmp.so                                   
lib64/librpmb.so                                  
lib64/librs_adreno_sha1.so                        
lib64/librs_adreno.so                             
lib64/libRSDriver_adreno.so                       
lib64/lib-rtpcommon.so                            
lib64/lib-rtpcore.so                              
lib64/lib-rtpdaemoninterface.so                   
lib64/lib-rtpsl.so                                
lib64/libSampleAuthJNI.so                         
lib64/libSampleExtAuthJNI.so                      
lib64/libscveBlobDescriptor.so                    
lib64/libscveBlobDescriptor_stub.so               
lib64/libscveCleverCapture.so                     
lib64/libscveCleverCapture_stub.so                
lib64/libscveCommon.so                            
lib64/libscveCommon_stub.so                       
lib64/libscveFaceLandmarks.so                     
lib64/libscveFaceLandmarks_stub.so                
lib64/libscveFaceRecognition.so                   
lib64/libscveFaceRecognition_stub.so              
lib64/libscveImageCloning.so                      
lib64/libscveImageCorrection.so                   
lib64/libscveImageRemoval.so                      
lib64/libscveMotionVector.so                      
lib64/libscveObjectMatting.so                     
lib64/libscveObjectMatting_stub.so                
lib64/libscveObjectSegmentation.so                
lib64/libscveObjectSegmentation_stub.so           
lib64/libscveObjectTracker.so                     
lib64/libscveObjectTracker_stub.so                
lib64/libscvePanorama_lite.so                     
lib64/libscvePanorama.so                          
lib64/libscveTextRecoPostProcessing.so            
lib64/libscveTextReco.so                          
lib64/libscveTextReco_stub.so                     
lib64/libscveVideoSummary.so                      
lib64/libscveVideoSummary_stub.so                 
lib64/libsdm-color.so                             
lib64/libsdm-diag.so                              
lib64/libsdm-disp-apis.so                         
lib64/libsdmextension.so                          
lib64/libsd_sdk_display.so                        
lib64/libsdsprpc.so                               
lib64/libseccam.so                                
lib64/libseccam_vendor.so                         
lib64/lib-sec-disp.so                             
lib64/libSecureExtAuthJNI.so                      
lib64/libSecureSampleAuthJNI.so                   
lib64/libSecureUILib.so                           
lib64/libsecureui.so                              
lib64/libsecureuisvc_jni.so                       
lib64/libsecureui_svcsock.so                      
lib64/libseemore.so                               
lib64/libseemp_binder.so                          
lib64/libSeemplog.so                              
lib64/libSeempMsgService.so                       
lib64/libseempnative.so                           
lib64/libsensor1.so                               
lib64/libsensor_reg.so                            
lib64/libsensor_test.so                           
lib64/libsensor_thresh.so                         
lib64/libsensor_user_cal.so                       
lib64/libsettings.so                              
lib64/libsi.so                                    
lib64/libslimclient.so                            
lib64/libsmcinvokecred.so                         
lib64/libsmemlog.so                               
lib64/libsns_low_lat_stream_stub.so               
lib64/libspcom.so                                 
lib64/libspl.so                                   
lib64/libssd.so                                   
lib64/libStDrvInt.so                              
lib64/libstreamparser.so                          
lib64/libsubsystem_control.so                     
lib64/libSubSystemShutdown.so                     
lib64/libsystem_health_mon.so                     
lib64/libthermalclient.so                         
lib64/libthermalioctl.so                          
lib64/libtime_genoff.so                           
lib64/libTimeService.so                           
lib64/libtinyxml2_1.so                            
lib64/libts_detected_face_hal.so                  
lib64/libts_detected_face_jni.so                  
lib64/libts_face_beautify_hal.so                  
lib64/libts_face_beautify_jni.so                  
lib64/libtzcom.so                                 
lib64/libtzdrmgenprov.so                          
lib64/libubifocus.so                              
lib64/libUBWC.so                                  
lib64/libulp2.so                                  
lib64/libvendorconn.so                            
lib64/libvideobokeh.so                            
lib64/libvideoutils.so                            
lib64/libvoice-svc.so                             
lib64/libvpphvx.so                                
lib64/libvr_amb_engine.so                         
lib64/libvraudio_client.so                        
lib64/libvraudio.so                               
lib64/libvr_object_engine.so                      
lib64/libvr_sam_wrapper.so                        
lib64/libwbc_jni.so                               
lib64/libwfdavenhancements.so                     
lib64/libwfdcommonutils.so                        
lib64/libwfdhdcpcp.so                             
lib64/libwfdmminterface.so                        
lib64/libwfdmmservice.so                          
lib64/libwfdmmsink.so                             
lib64/libwfdmmsrc.so                              
lib64/libwfdnative.so                             
lib64/libwfdrtsp.so                               
lib64/libwfdservice.so                            
lib64/libwfdsm.so                                 
lib64/libwfduibcinterface.so                      
lib64/libwfduibcsinkinterface.so                  
lib64/libwfduibcsink.so                           
lib64/libwfduibcsrcinterface.so                   
lib64/libwfduibcsrc.so                            
lib64/libwms.so                                   
lib64/libwqe.so                                   
lib64/libxml.so                                   
lib64/libxtadapter.so                             
lib64/libxt_native.so                             
lib64/libxtwifi_ulp_adaptor.so                    
lib64/mmi_audio.so                                
lib64/mmi_battery.so                              
lib64/mmi_bluetooth.so                            
lib64/mmi_cpu.so                                  
lib64/mmi_flashlight.so                           
lib64/mmi_fm.so                                   
lib64/mmi_gps.so                                  
lib64/mmi_headset.so                              
lib64/mmi_key.so                                  
lib64/mmi_lcd.so                                  
lib64/mmi_light.so                                
lib64/mmi_memory.so                               
lib64/mmi_nfc.so                                  
lib64/mmi_power.so                                
lib64/mmi_sensor.so                               
lib64/mmi_sim.so                                  
lib64/mmi_storage.so                              
lib64/mmi_sysinfo.so                              
lib64/mmi_telephone.so                            
lib64/mmi_touch.so                                
lib64/mmi_vibrator.so                             
lib64/mmi_wifi.so                                 
lib64/sensor_calibrate.so                         
lib64/sensors.ssc.so                              
lib64/soundfx/libqcbassboost.so                   
lib64/soundfx/libqcreverb.so                      
lib64/soundfx/libqcvirt.so                        
qcril.db  
lib64/libgpustats.so
lib/libgpustats.so
lib64/libqmi_cci.so
lib/libqmi_cci.so
lib64/libqmiservices.so
lib/libqmiservices.so
lib64/libidl.so
lib/libidl.so
lib64/libqmi_common_so.so
lib/libqmi_common_so.so
lib64/libdsi_netctrl.so
lib/libdsi_netctrl.so
lib/libfusionLibrary.so
lib/libStDualCam.so
lib/libVDDualCameraBlurlessAPI.so
lib/libchromatix_imx398_3a_4608x3456_30fps_preview_bokeh.so
lib/libchromatix_imx398_3a_4656x3496_30fps_video.so
lib/libchromatix_imx398_cpp_4608x3456_snapshot_bokeh.so
lib/libchromatix_imx398_cpp_4656x3496_30fps_video.so
lib/libchromatix_imx398_isp_4656x3496_30fps_video.so
"          


for i in ${vendor_list}
do
  adb pull /system/vendor/${i} ${PREBUILT_PATH}vendor/${i}
done

framework_list=" 
com.fingerprints.extension.jar
"

for i in ${framework_list}
do
  adb pull /system/framework/${i} ${PREBUILT_PATH}framework/${i}
done

xbin_list="
"

for i in ${xbin_list}
do
  adb pull /system/xbin/${i} ${PREBUILT_PATH}xbin/${i}
done

sbin_list="
dashd
"

for i in ${sbin_list}
do
  adb pull /sbin/${i} ${PREBUILT_PATH}sbin/${i}
done
                     
