#!/bin/bash

PREBUILT_PATH="vendor/oneplus/"

list="
bin
sbin
etc
etc/camera
etc/cne
etc/data
etc/dpm
etc/dpm/nsrm
etc/drc
etc/firmware
etc/hostapd
etc/init
etc/mmi
etc/mmi/layout
etc/perf
etc/permissions
etc/qvop
etc/sensors
etc/surround_sound
etc/surround_sound_3mic
etc/usf
etc/usf/mixer
etc/usf/proximity
etc/usf/proximity/cfg_mtp
framework
lib
lib64
lib64/hw
lib64/soundfx
lib/hw
lib/modules
lib/rfsa/adsp
lib/soundfx
vendor
vendor/bin
vendor/bin/hw
vendor/bin/qmi-framework-tests
vendor/etc
vendor/etc/acdbdata/MTP
vendor/etc/data
vendor/etc/drc
vendor/etc/init
vendor/etc/perf
vendor/etc/qti-logkit
vendor/etc/qvr
vendor/etc/RIDL
vendor/etc/scve/facereco
vendor/etc/scve/textreco/chardecoder
vendor/etc/scve/textreco/textdetector
vendor/etc/scve/textreco/worddecoder
vendor/etc/sensors
vendor/etc/surround_sound_3mic
vendor/etc/wifi
vendor/firmware
vendor/lib
vendor/lib64
vendor/lib64/egl
vendor/lib64/hw
vendor/lib64/soundfx
vendor/lib/egl
vendor/lib/hw
vendor/lib/mediadrm
vendor/lib/qcdrm/playready/lib
vendor/lib/qcdrm/playready/lib/drm
vendor/lib/qcdrm/playready/lib/mediadrm
vendor/radio/qcril_database
vendor/lib/rfsa/adsp
vendor/lib/soundfx
xbin
"

for i in ${list}
do
  mkdir -p ${PREBUILT_PATH}${i}
done

bin_list="
cnss-daemon
dpmd					
dun-server
ifaadaemon	
fmconfig				
fmfactorytest			
fmfactorytestserver		
ks						
pktlogconf				
Proximity_calib			
Proximity_tester		
qvrservice
test_bet_8996		
test_module_pproc	
tloc_daemon			
wfdservice
"		

for i in ${bin_list}
do
  adb pull /system/bin/${i} ${PREBUILT_PATH}bin/${i}
done

cd ${PREBUILT_PATH}bin
chmod 775 *
cd -

etc_list="
apns-conf.xml
camera/camera_config.xml
camera/csidtg_camera.xml
camera/csidtg_chromatix.xml
camera/imx179_chromatix.xml
camera/imx298_chromatix.xml
camera/s5k3p8_chromatix.xml
camera/s5k3p8sp_chromatix.xml
cdma_call_conf.xml
cne/andsfCne.xml
cne/SwimConfig.xml
dpm/dpm.conf
dpm/nsrm/NsrmConfiguration.xml
firmware/cpp_firmware_v1_10_0.fw
firmware/cpp_firmware_v1_1_1.fw
firmware/cpp_firmware_v1_12_0.fw
firmware/cpp_firmware_v1_1_6.fw
firmware/cpp_firmware_v1_2_0.fw
firmware/cpp_firmware_v1_4_0.fw
firmware/cpp_firmware_v1_5_0.fw
firmware/cpp_firmware_v1_5_1.fw
firmware/cpp_firmware_v1_5_2.fw
firmware/cpp_firmware_v1_6_0.fw
firmware/cpp_firmware_v1_8_0.fw
hostapd/hostapd.accept
hostapd/hostapd_default.conf
hostapd/hostapd.deny
init/dpmd.rc
init/wfdservice.rc
mmi/fail.png
mmi/fonts.ttf
mmi/layout/footer_fail.xml
mmi/layout/footer.xml
mmi/layout/header.xml
mmi/layout/layout_battery.xml
mmi/layout/layout_bluetooth.xml
mmi/layout/layout_button_backlight.xml
mmi/layout/layout_camera_back.xml
mmi/layout/layout_camera_front.xml
mmi/layout/layout_cb.xml
mmi/layout/layout_common.xml
mmi/layout/layout_confirm.xml
mmi/layout/layout_cpu.xml
mmi/layout/layout_emmc.xml
mmi/layout/layout_feedback.xml
mmi/layout/layout_flashlight.xml
mmi/layout/layout_fm.xml
mmi/layout/layout_gps.xml
mmi/layout/layout_gsensor.xml
mmi/layout/layout_gyroscope.xml
mmi/layout/layout_handset.xml
mmi/layout/layout_headset_key.xml
mmi/layout/layout_headset.xml
mmi/layout/layout_hsensor.xml
mmi/layout/layout_indicator.xml
mmi/layout/layout_keypad.xml
mmi/layout/layout_key.xml
mmi/layout/layout_lcd_backlight.xml
mmi/layout/layout_lcd.xml
mmi/layout/layout_led_blue.xml
mmi/layout/layout_led_green.xml
mmi/layout/layout_led_red.xml
mmi/layout/layout_loudspeaker.xml
mmi/layout/layout_lsensor.xml
mmi/layout/layout_memory.xml
mmi/layout/layout_msensor.xml
mmi/layout/layout_nfc.xml
mmi/layout/layout_pcba.xml
mmi/layout/layout_power.xml
mmi/layout/layout_primary_mic.xml
mmi/layout/layout_psensor.xml
mmi/layout/layout_reboot.xml
mmi/layout/layout_report.xml
mmi/layout/layout_sdcard.xml
mmi/layout/layout_simcard1.xml
mmi/layout/layout_simcard2.xml
mmi/layout/layout_system_info.xml
mmi/layout/layout_telephone.xml
mmi/layout/layout_touch.xml
mmi/layout/layout_vibrator.xml
mmi/layout/layout_wifi.xml
mmi/layout/main_wear.xml
mmi/layout/main.xml
mmi/mmi.xml
mmi/pagedown.png
mmi/pageup.png
mmi/pass.png
mmi/path_config.xml
mmi/poweroff.png
mmi/qualsound.wav
mmi/reboot.png
mmi/report.png
mmi/reset.png
mmi/runall.png
mmi/strings.xml
mmi/strings-zh-rCN.xml
perf/whitelistedapps.xml
permissions/android.hardware.fingerprint.xml
permissions/android.hardware.light.xml
permissions/audiosphere.xml
permissions/btmultisim.xml
permissions/cneapiclient.xml
permissions/com.qti.dpmframework.xml
permissions/com.qti.location.sdk.xml
permissions/com.qti.snapdragon.sdk.display.xml
permissions/com.qualcomm.location.xml
permissions/com.quicinc.cne.xml
permissions/dpmapi.xml
permissions/embms.xml
permissions/izat.xt.srv.xml
permissions/lpa.xml
permissions/qcnvitems.xml
permissions/qcrilhook.xml
permissions/qti_libpermissions.xml
permissions/qti_permissions.xml
permissions/qti-vzw-ims-internal.xml
permissions/telephonyservice.xml
usf/proximity/usf_proximity_calib.sh
usf_settings.sh
wfdconfigsink.xml
wfdconfig.xml
libnfc-nxp.conf                                    
libnfc-brcm.conf
"

for i in ${etc_list}
do
  adb pull /system/etc/${i} ${PREBUILT_PATH}etc/${i}
done

lib_list="
hw/fingerprint.msm8996.so
android.hardware.audio@2.0.so
android.hardware.broadcastradio@1.1.so
android.hardware.tests.libhwbinder@1.0.so
com.qualcomm.qti.ant@1.0.so
com.qualcomm.qti.bluetooth_audio@1.0.so
com.qualcomm.qti.dpm.api@1.0.so
com.qualcomm.qti.imscmservice@1.0.so
com.qualcomm.qti.wifidisplayhal@1.0.so
fm_helium.so
lib_fpc_tac_shared.so
libadsprpc.so
libantradio.so
libavenhancements.so
libcdsprpc.so
libdiag_system.so
libdisplayconfig.so
libdpmctmgr.so
libdpmfdmgr.so
libdpmframework.so
libdpmnsrm.so
libdpmtcm.so
libdualcameraddm.so
libcom_fingerprints_service.so
libExtendedExtractor.so
libFidoCryptoJNI.so
libFidoCrypto_system.so
libFileMux.so
libfiltergenerator.so
libfm-hci.so
libGPTEE_system.so
libhazebuster.so
libimscamera_jni.so
lib-imscamera.so
libimsmedia_jni.so
lib-imsvideocodec.so
lib-imsvtextutils.so
lib-imsvt.so
lib-imsvtutils.so
libjni_dualcamera.so
libjni_filtergenerator.so
libjni_hazebuster.so
libjni_makeupV2.so
libjni_optizoom.so
libjni_seestraight.so
libjni_sharpshooter.so
libjni_trueportrait.so
libjni_truescanner_v2.so
libjni_ubifocus.so
liblistenjni.so
liblistensoundmodel2.so
liblocationservice_jni.so
libmm-qcamera.so
libmdsprpc.so
libminui.so
libmmosal.so
libmmparser_lite.so
libmmparser.so
libmmrtpdecoder.so
libmmrtpencoder.so
libOmxMux.so
libparam.so
libqct_resampler.so
libqmi_cci_system.so
libqomx_core.so
libqsap_sdk.so
libQTEEConnector_system.so
libqti-at.so
libqti-perfd-client_system.so
libqti_performance.so
libqti-util_system.so
libqvr_adsp_driver_skel.so
libqvr_adsp_driver_stub.so
libqvrservice.so
librcc.so
libsdm-disp-apis.so
libsdsprpc.so
libseemore.so
libSeemplog.so
libseestraight.so
libsensor1.so
libsensor_reg.so
libsensor_test.so
libstagefright_soft_flacdec.so
libteeclientjni.so
libtrueportrait.so
libtruescanner.so
libts_detected_face_jni.so
libts_face_beautify_hal.so
libts_face_beautify_jni.so
libvendorconn.so
libvr_amb_engine.so
libvraudio_client.so
libvraudio.so
libvr_object_engine.so
libvr_sam_wrapper.so
libwbc_jni.so
libwfdavenhancements.so
libwfdcodecv4l2.so
libwfdcommonutils.so
libwfdconfigutils.so
libwfdmminterface.so
libwfdmmsink.so
libwfdmmsrc.so
libwfdnative.so
libwfdrtsp.so
libwfdservice.so
libwfdsm.so
libwfduibcinterface.so
libwfduibcsinkinterface.so
libwfduibcsink.so
libwfduibcsrcinterface.so
libwfduibcsrc.so
libxt_native.so
modules/defrag.ko
qpd_dspcl_v2.bin
TC_Bayer_Converter_v6_core_opt.bin
vendor.display.color@1.0.so
vendor.display.config@1.0.so
vendor.display.postproc@1.0.so
vendor.qti.esepowermanager@1.0.so
vendor.qti.gnss@1.0.so
vendor.qti.hardware.fm@1.0.so
vendor.qti.hardware.iop@1.0.so
vendor.qti.hardware.perf@1.0.so
vendor.qti.hardware.qteeconnector@1.0.so
vendor.qti.imsrtpservice@1.0.so
libopcamera_native_modules.so
libmms_gyro_vstab.so
libmms_hal_vstab.so
libmms_warper_vstab.so
libSensorManagerHAL.so
libFNVfbEngineHAL.so
libmorpho_video_refiner.so
libmorpho_image_stab4.so
lib_oneplus_md.so
lib_oneplus_facebeauty.so
lib_oneplus_watermark.so
libmms_gyro_vstab_auth.so
"

for i in ${lib_list}
do
  adb pull /system/lib/${i} ${PREBUILT_PATH}lib/${i}
done

lib64_list="
hw/fingerprint.msm8996.so
hw/nfc_nci.pn54x.default.so
android.hardware.audio@2.0.so
android.hardware.biometrics.fingerprint@2.1.so
android.hardware.tests.libhwbinder@1.0.so
android.hardware.wifi@1.0.so
android.hardware.wifi.supplicant@1.0.so
com.qualcomm.qti.ant@1.0.so
com.qualcomm.qti.bluetooth_audio@1.0.so
com.qualcomm.qti.dpm.api@1.0.so
com.qualcomm.qti.imscmservice@1.0.so
com.qualcomm.qti.wifidisplayhal@1.0.so
fm_helium.so
lib_fpc_tac_shared.so
libadsprpc.so
libantradio.so
libavenhancements.so
libcdsprpc.so
libclearsight.so
libcom_fingerprints_service.so
libdiag_system.so
libdisplayconfig.so
libdpmctmgr.so
libdpmfdmgr.so
libdpmframework.so
libdpmnsrm.so
libdpmtcm.so
libdualcameraddm.so
libExtendedExtractor.so
libFidoCryptoJNI.so
libFidoCrypto_system.so
libFileMux.so
libfiltergenerator.so
libfm-hci.so
libGPTEE_system.so
libhazebuster.so
libimscamera_jni.so
lib-imscamera.so
libimsmedia_jni.so
lib-imsvideocodec.so
lib-imsvtextutils.so
lib-imsvt.so
lib-imsvtutils.so
libjni_clearsight.so
libjni_dualcamera.so
libjni_filtergenerator.so
libjni_hazebuster.so
libjni_makeupV2.so
libjni_optizoom.so
libjni_seestraight.so
libjni_sharpshooter.so
libjni_trueportrait.so
libjni_truescanner_v2.so
libjni_ubifocus.so
liblistenjni.so
liblistensoundmodel2.so
liblocationservice_jni.so
libmdsprpc.so
libminui.so
libmmosal.so
libmmparser_lite.so
libmmparser.so
libmmrtpdecoder.so
libmmrtpencoder.so
libOmxMux.so
libparam.so
libqmi_cci_system.so
libQTEEConnector_system.so
libqti-at.so
libqti-perfd-client_system.so
libqti_performance.so
libqti-util_system.so
librcc.so
libsdm-disp-apis.so
libsdsprpc.so
libseemore.so
libSeemplog.so
libseestraight.so
libsensor1.so
libsensor_reg.so
libsensor_test.so
libstagefright_soft_flacdec.so
libteeclientjni.so
libteeclientjniv2.so
libtrueportrait.so
libtruescanner.so
libts_detected_face_jni.so
libts_face_beautify_hal.so
libts_face_beautify_jni.so
libvendorconn.so
libvr_amb_engine.so
libvraudio_client.so
libvraudio.so
libvr_object_engine.so
libvr_sam_wrapper.so
libwbc_jni.so
libwfdavenhancements.so
libwfdcodecv4l2.so
libwfdcommonutils.so
libwfdconfigutils.so
libwfdmminterface.so
libwfdmmsink.so
libwfdmmsrc.so
libwfdnative.so
libwfdrtsp.so
libwfdservice.so
libwfdsm.so
libwfduibcinterface.so
libwfduibcsinkinterface.so
libwfduibcsink.so
libwfduibcsrcinterface.so
libwfduibcsrc.so
libxt_native.so
vendor.display.color@1.0.so
vendor.display.config@1.0.so
vendor.display.postproc@1.0.so
vendor.qti.esepowermanager@1.0.so
vendor.qti.gnss@1.0.so
vendor.qti.hardware.fm@1.0.so
vendor.qti.hardware.iop@1.0.so
vendor.qti.hardware.perf@1.0.so
vendor.qti.hardware.qteeconnector@1.0.so
vendor.qti.hardware.wifi.supplicant@1.0.so
vendor.qti.imsrtpservice@1.0.so
libnfc-nci.so                                    
libnfc_nci_jni.so       
libp61-jcop-kit.so  
"

for i in ${lib64_list}
do
  adb pull /system/lib64/${i} ${PREBUILT_PATH}lib64/${i}
done

usr_list="
"

for i in ${usr_list}
do
  adb pull /system/usr/${i} ${PREBUILT_PATH}usr/${i}
done

vendor_list="
bin/adsprpcd
bin/ATFWD-daemon
bin/athdiag
bin/audioflacapp
bin/btnvtool
bin/cnd
bin/diag_callback_sample
bin/diag_dci_sample
bin/diag_klog
bin/diag_mdlog
bin/diag_socket_log
bin/diag_uart_log
bin/dpmQmiMgr
bin/DR_AP_Service
bin/e_loop
bin/energy-awareness
bin/fm_qsoc_patches
bin/ftmdaemon
bin/gamed
bin/garden_app
bin/hal_proxy_daemon
bin/hci_qcomm_init
bin/hdcp1prov
bin/hdcp2p2prov
bin/hostapd
bin/hostapd_cli
bin/hvdcp_opti
bin/hw/android.hardware.audio@2.0-service
bin/hw/android.hardware.biometrics.fingerprint@2.1-service
bin/hw/android.hardware.bluetooth@1.0-service-qti
bin/hw/android.hardware.sensors@1.0-service
bin/hw/android.hardware.wifi@1.0-service
bin/hw/vendor.display.color@1.0-service
bin/hw/vendor.qti.esepowermanager@1.0-service
bin/hw/vendor.qti.gnss@1.0-service
bin/hw/vendor.qti.hardware.iop@1.0-service
bin/hw/vendor.qti.hardware.perf@1.0-service
bin/hw/vendor.qti.hardware.qteeconnector@1.0-service
bin/imsdatadaemon
bin/imsqmidaemon
bin/imsrcsd
bin/ims_rtp_daemon
bin/ipacm-diag
bin/irsc_util
bin/loc_launcher
bin/lowi-server
bin/mdm_helper_proxy
bin/mm-audio-ftm
bin/mm-pp-dpps
bin/mm-qcamera-daemon
bin/mm-qjpeg-dec-test
bin/mm-qjpeg-enc-test
bin/mm-qomx-ienc-test
bin/mm-vidc-omx-test
bin/msm_irqbalance
bin/myftm
bin/netmgrd
bin/PktRspTest
bin/pm-proxy
bin/pm-service
bin/port-bridge
bin/qjpeg-dma-test
bin/qmi-framework-tests/qmi_test_mt_client_init_instance
bin/qmi_simple_ril_test
bin/qseecomd
bin/qseecom_sample_client
bin/qti
bin/remosaic_daemon
bin/rmt_storage
bin/sensors.qcom
bin/slim_daemon
bin/sns_ar_testapp
bin/sns_cm_conc_test
bin/sns_cm_test
bin/sns_dsps_tc0001
bin/sns_hal_batch
bin/sns_oem_test
bin/sns_regedit_ssi
bin/ssr_diag
bin/ssr_setup
bin/StoreKeybox
bin/subsystem_ramdump
bin/tbaseLoader
bin/test_diag
bin/tftp_server
bin/thermal-engine
bin/time_daemon
bin/wcnss_filter
bin/wdsdaemon
bin/wifidisplayhalservice
bin/WifiLogger_app
bin/xtra-daemon
bin/xtwifi-client
bin/xtwifi-inet-agent
etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb
etc/acdbdata/MTP/MTP_General_cal.acdb
etc/acdbdata/MTP/MTP_Global_cal.acdb
etc/acdbdata/MTP/MTP_Handset_cal.acdb
etc/acdbdata/MTP/MTP_Hdmi_cal.acdb
etc/acdbdata/MTP/MTP_Headset_cal.acdb
etc/acdbdata/MTP/MTP_Speaker_cal.acdb
etc/apdr.conf
etc/cacert_location.pem
etc/data/dsi_config.xml
etc/data/netmgr_config.xml
etc/drc/drc_cfg_5.1.txt
etc/drc/drc_cfg_AZ.txt
etc/flp.conf
etc/ftm_test_config
etc/ftm_test_config_msm8996-dtp-tasha-snd-card
etc/gps.conf
etc/init/android.hardware.audio@2.0-service.rc
etc/init/android.hardware.bluetooth@1.0-service-qti.rc
etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc
etc/init/android.hardware.sensors@1.0-service.rc
etc/init/android.hardware.wifi@1.0-service.rc
etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc
etc/init/hostapd.android.rc
etc/init/vendor.display.color@1.0-service.rc
etc/init/vendor.qti.esepowermanager@1.0-service.rc
etc/init/vendor.qti.gnss@1.0-service.rc
etc/init/vendor.qti.hardware.iop@1.0-service.rc
etc/init/vendor.qti.hardware.perf@1.0-service.rc
etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc
etc/izat.conf
etc/lowi.conf
etc/perf/gamedwhitelist.xml
etc/perf/perfboostsconfig.xml
etc/perf/perf-profile0.conf
etc/perf/perf-profile1.conf
etc/perf/perf-profile2.conf
etc/perf/perf-profile3.conf
etc/perf/perf-profile4.conf
etc/perf/perf-profile5.conf
etc/perf/perf-profile6.conf
etc/public.libraries.txt
etc/qvr/qvrservice_6dof_config.xml
etc/qvr/qvrservice_config.txt
etc/sap.conf
etc/sensors/sensor_def_qcomdev.conf
etc/surround_sound_3mic/surround_sound_rec_5.1.cfg
etc/surround_sound_3mic/surround_sound_rec_AZ.cfg
etc/thermal-engine.conf
etc/wifi/p2p_supplicant_overlay.conf
etc/wifi/wpa_supplicant.conf
etc/wifi/wpa_supplicant_overlay.conf
etc/xtra_root_cert.pem
etc/xtwifi.conf
firmware/a225p5_pm4.fw
firmware/a300_pfp.fw          
firmware/a300_pm4.fw            
firmware/a330_pfp.fw            
firmware/a330_pm4.fw            
firmware/a420_pfp.fw            
firmware/a420_pm4.fw            
firmware/a530_gpmu.fw2         
firmware/a530_pfp.fw          
firmware/a530_pm4.fw            
firmware/a530_zap.b00          
firmware/a530_zap.b01           
firmware/a530_zap.b02           
firmware/a530_zap.elf           
firmware/a530_zap.mdt           
firmware/a530v1_pfp.fw       
firmware/a530v1_pm4.fw          
firmware/a530v2_seq.fw2         
firmware/a530v3_gpmu.fw2        
firmware/a530v3_seq.fw2         
firmware/a540_gpmu.fw2          
firmware/leia_pfp_470.fw        
firmware/leia_pm4_470.fw        
firmware/libpn547_fw.so         
firmware/libpn548ad_fw.so       
firmware/libpn551_fw.so         
firmware/libpn553_fw.so         
firmware/libpn557_fw.so
lib/com.qualcomm.qti.ant@1.0_vendor.so
lib/com.qualcomm.qti.bluetooth_audio@1.0_vendor.so
lib/com.qualcomm.qti.dpm.api@1.0_vendor.so
lib/com.qualcomm.qti.imscmservice@1.0_vendor.so
lib/com.qualcomm.qti.wifidisplayhal@1.0-halimpl.so
lib/com.qualcomm.qti.wifidisplayhal@1.0-impl.so
lib/com.qualcomm.qti.wifidisplayhal@1.0_vendor.so
lib/com.quicinc.cne.api@1.0.so
lib/com.quicinc.cne.constants@1.0.so
lib/com.quicinc.cne.constants@2.0.so
lib/com.quicinc.cne.server@1.0.so
lib/com.quicinc.cne.server@2.0.so
lib/egl/eglSubDriverAndroid.so
lib/egl/libEGL_adreno.so
lib/egl/libGLESv1_CM_adreno.so
lib/egl/libGLESv2_adreno.so
lib/egl/libq3dtools_adreno.so
lib/egl/libq3dtools_esx.so
lib/egl/libQTapGLES.so
lib/hw/activity_recognition.msm8996.so
lib/hw/android.hardware.audio@2.0-impl.so
lib/hw/android.hardware.bluetooth@1.0-impl-qti.so
lib/hw/android.hardware.gnss@1.0-impl-qti.so
lib/hw/android.hardware.renderscript@1.0-impl.so
lib/hw/android.hardware.sensors@1.0-impl.so
lib/hw/android.hardware.tests.libhwbinder@1.0-impl.so
lib/hw/camera.msm8996.so
lib/hw/com.qualcomm.qti.ant@1.0-impl.so
lib/hw/gatekeeper.msm8996.so
lib/hw/keystore.msm8996.so
lib/hw/lights.msm8996.so
lib/hw/sound_trigger.primary.msm8996.so
lib/hw/vendor.qti.esepowermanager@1.0-impl.so
lib/hw/vendor.qti.gnss@1.0-impl.so
lib/hw/vendor.qti.hardware.fm@1.0-impl.so
lib/hw/vendor.qti.hardware.iop@1.0-impl.so
lib/hw/vendor.qti.hardware.qteeconnector@1.0-impl.so
lib/hw/vulkan.msm8996.so
lib/libacdb-fts.so
lib/libacdbloader.so
lib/libacdbmapper.so
lib/libacdbrtac.so
lib/libactuator_rohm_bu63165gwl.so
lib/libadiertac.so
lib/libadm.so
lib/libadpcmdec.so
lib/libadreno_utils.so
lib/libadsp_default_listener.so
lib/libadsp_hvx_callback_skel.so
lib/libadsp_hvx_stub.so
lib/libadsprpc.so
lib/libAlacSwDec.so
lib/libalarmservice_jni.so
lib/libApeSwDec.so
lib/libAR_jni.so
lib/libaudcal.so
lib/libaudioalsa.so
lib/libaudio_log_utils.so
lib/libbccQTI.so
lib/libbt-hidlclient.so
lib/libbtnv.so
lib/libbt-vendor.so
lib/libC2D2.so
lib/libc2d30-a3xx.so
lib/libc2d30-a4xx.so
lib/libc2d30-a5xx.so
lib/libc2d30_bltlib.so
lib/libc2dcolorconvert.so
lib/libCB.so
lib/libcdsprpc.so
lib/libchromaflash.so
lib/libchromatix_imx179_3a_1640x924_30fps_preview.so
lib/libchromatix_imx179_3a_1640x924_30fps_preview_x3.so
lib/libchromatix_imx179_3a_1640x924_30fps_video.so
lib/libchromatix_imx179_3a_1640x924_30fps_video_x3.so
lib/libchromatix_imx179_3a_3280x1846_30fps_preview.so
lib/libchromatix_imx179_3a_3280x1846_30fps_preview_x3.so
lib/libchromatix_imx179_3a_3280x1846_30fps_video.so
lib/libchromatix_imx179_3a_3280x1846_30fps_video_x3.so
lib/libchromatix_imx179_3a_3280x2464_30fps_facebeauty.so
lib/libchromatix_imx179_3a_3280x2464_30fps_facebeauty_x3.so
lib/libchromatix_imx179_3a_3280x2464_30fps_preview.so
lib/libchromatix_imx179_3a_3280x2464_30fps_preview_x3.so
lib/libchromatix_imx179_3a_3280x2464_30fps_video.so
lib/libchromatix_imx179_3a_3280x2464_30fps_video_x3.so
lib/libchromatix_imx179_common.so
lib/libchromatix_imx179_cpp_1640x924_30fps_preview.so
lib/libchromatix_imx179_cpp_1640x924_30fps_snapshot.so
lib/libchromatix_imx179_cpp_1640x924_30fps_video.so
lib/libchromatix_imx179_cpp_3280x1846_30fps_preview.so
lib/libchromatix_imx179_cpp_3280x1846_30fps_snapshot.so
lib/libchromatix_imx179_cpp_3280x1846_30fps_video.so
lib/libchromatix_imx179_cpp_3280x2464_30fps_facebeauty.so
lib/libchromatix_imx179_cpp_3280x2464_30fps_nomultiframe.so
lib/libchromatix_imx179_cpp_3280x2464_30fps_preview.so
lib/libchromatix_imx179_cpp_3280x2464_30fps_snapshot.so
lib/libchromatix_imx179_cpp_3280x2464_30fps_video.so
lib/libchromatix_imx179_isp_1640x924_30fps_preview.so
lib/libchromatix_imx179_isp_1640x924_30fps_preview_x3.so
lib/libchromatix_imx179_isp_1640x924_30fps_snapshot.so
lib/libchromatix_imx179_isp_1640x924_30fps_snapshot_x3.so
lib/libchromatix_imx179_isp_1640x924_30fps_video.so
lib/libchromatix_imx179_isp_1640x924_30fps_video_x3.so
lib/libchromatix_imx179_isp_3280x1846_30fps_preview.so
lib/libchromatix_imx179_isp_3280x1846_30fps_preview_x3.so
lib/libchromatix_imx179_isp_3280x1846_30fps_snapshot.so
lib/libchromatix_imx179_isp_3280x1846_30fps_snapshot_x3.so
lib/libchromatix_imx179_isp_3280x1846_30fps_video.so
lib/libchromatix_imx179_isp_3280x1846_30fps_video_x3.so
lib/libchromatix_imx179_isp_3280x2464_30fps_facebeauty.so
lib/libchromatix_imx179_isp_3280x2464_30fps_facebeauty_x3.so
lib/libchromatix_imx179_isp_3280x2464_30fps_preview.so
lib/libchromatix_imx179_isp_3280x2464_30fps_preview_x3.so
lib/libchromatix_imx179_isp_3280x2464_30fps_snapshot.so
lib/libchromatix_imx179_isp_3280x2464_30fps_snapshot_x3.so
lib/libchromatix_imx179_isp_3280x2464_30fps_video.so
lib/libchromatix_imx179_isp_3280x2464_30fps_video_x3.so
lib/libchromatix_imx179_postproc.so
lib/libchromatix_imx298_3a_clearshot.so
lib/libchromatix_imx298_3a_clearshot_s.so
lib/libchromatix_imx298_3a_HDR.so
lib/libchromatix_imx298_3a_HDR_s.so
lib/libchromatix_imx298_3a_panorama.so
lib/libchromatix_imx298_3a_panorama_s.so
lib/libchromatix_imx298_4K_preview.so
lib/libchromatix_imx298_4K_preview_s.so
lib/libchromatix_imx298_4K_video.so
lib/libchromatix_imx298_4K_video_s.so
lib/libchromatix_imx298_common_60fps.so
lib/libchromatix_imx298_common_clearshot.so
lib/libchromatix_imx298_common_manual.so
lib/libchromatix_imx298_common.so
lib/libchromatix_imx298_cpp_hfr_120.so
lib/libchromatix_imx298_cpp_hfr_60.so
lib/libchromatix_imx298_cpp_hfr_90.so
lib/libchromatix_imx298_cpp_panorama_preview.so
lib/libchromatix_imx298_cpp_panorama_snapshot.so
lib/libchromatix_imx298_cpp_preview.so
lib/libchromatix_imx298_cpp_snapshot_clearshot.so
lib/libchromatix_imx298_cpp_snapshot_flash.so
lib/libchromatix_imx298_cpp_snapshot_hdr.so
lib/libchromatix_imx298_cpp_snapshot_manual.so
lib/libchromatix_imx298_cpp_snapshot_nomultiframe.so
lib/libchromatix_imx298_cpp_snapshot.so
lib/libchromatix_imx298_cpp_video_4k.so
lib/libchromatix_imx298_cpp_video_preview.so
lib/libchromatix_imx298_cpp_video.so
lib/libchromatix_imx298_default_preview.so
lib/libchromatix_imx298_default_preview_s.so
lib/libchromatix_imx298_default_video.so
lib/libchromatix_imx298_default_video_s.so
lib/libchromatix_imx298_hfr_120_3a.so
lib/libchromatix_imx298_hfr_120_3a_s.so
lib/libchromatix_imx298_hfr_120.so
lib/libchromatix_imx298_hfr_60_3a.so
lib/libchromatix_imx298_hfr_60_3a_s.so
lib/libchromatix_imx298_hfr_60.so
lib/libchromatix_imx298_hfr_90_3a.so
lib/libchromatix_imx298_hfr_90_3a_s.so
lib/libchromatix_imx298_hfr_90.so
lib/libchromatix_imx298_isp_panorama.so
lib/libchromatix_imx298_postproc.so
lib/libchromatix_imx298_preview.so
lib/libchromatix_imx298_snapshot.so
lib/libchromatix_imx298_video.so
lib/libchromatix_imx298_zsl_preview.so
lib/libchromatix_imx298_zsl_preview_s.so
lib/libchromatix_imx298_zsl_video.so
lib/libchromatix_imx298_zsl_video_s.so
lib/libchromatix_s5k3p8_common.so
lib/libchromatix_s5k3p8_cpp_hfr_120.so
lib/libchromatix_s5k3p8_cpp_hfr_60.so
lib/libchromatix_s5k3p8_cpp_hfr_90.so
lib/libchromatix_s5k3p8_cpp_liveshot.so
lib/libchromatix_s5k3p8_cpp_preview.so
lib/libchromatix_s5k3p8_cpp_snapshot.so
lib/libchromatix_s5k3p8_cpp_video.so
lib/libchromatix_s5k3p8_default_preview_bu64297.so
lib/libchromatix_s5k3p8_default_video_bu64297.so
lib/libchromatix_s5k3p8_default_video.so
lib/libchromatix_s5k3p8_hfr_120_bu64297.so
lib/libchromatix_s5k3p8_hfr_120.so
lib/libchromatix_s5k3p8_hfr_60_bu64297.so
lib/libchromatix_s5k3p8_hfr_60.so
lib/libchromatix_s5k3p8_hfr_90_bu64297.so
lib/libchromatix_s5k3p8_hfr_90.so
lib/libchromatix_s5k3p8_postproc.so
lib/libchromatix_s5k3p8_preview.so
lib/libchromatix_s5k3p8_snapshot.so
lib/libchromatix_s5k3p8sp_3a_2304x1728_30fps_preview.so
lib/libchromatix_s5k3p8sp_3a_2304x1728_30fps_video.so
lib/libchromatix_s5k3p8sp_3a_4608x3456_30fps_preview.so
lib/libchromatix_s5k3p8sp_3a_4608x3456_30fps_video.so
lib/libchromatix_s5k3p8sp_common_2304x1728.so
lib/libchromatix_s5k3p8sp_common_4608x3456.so
lib/libchromatix_s5k3p8sp_cpp_2304x1728_30fps_liveshot.so
lib/libchromatix_s5k3p8sp_cpp_2304x1728_30fps_preview.so
lib/libchromatix_s5k3p8sp_cpp_2304x1728_30fps_snapshot.so
lib/libchromatix_s5k3p8sp_cpp_2304x1728_30fps_video.so
lib/libchromatix_s5k3p8sp_cpp_4608x3456_30fps_liveshot.so
lib/libchromatix_s5k3p8sp_cpp_4608x3456_30fps_preview.so
lib/libchromatix_s5k3p8sp_cpp_4608x3456_30fps_snapshot.so
lib/libchromatix_s5k3p8sp_cpp_4608x3456_30fps_video.so
lib/libchromatix_s5k3p8sp_isp_2304x1728_30fps_preview.so
lib/libchromatix_s5k3p8sp_isp_2304x1728_30fps_snapshot.so
lib/libchromatix_s5k3p8sp_isp_2304x1728_30fps_video.so
lib/libchromatix_s5k3p8sp_isp_4608x3456_30fps_preview.so
lib/libchromatix_s5k3p8sp_isp_4608x3456_30fps_snapshot.so
lib/libchromatix_s5k3p8sp_isp_4608x3456_30fps_video.so
lib/libchromatix_s5k3p8sp_postproc.so
lib/libchromatix_s5k3p8_zsl_preview_bu64297.so
lib/libchromatix_s5k3p8_zsl_video_bu64297.so
lib/libcneapiclient.so
lib/libcneoplookup.so
lib/libcneqmiutils.so
lib/libcne.so
lib/libconfigdb.so
lib/libcppf.so
lib/libcsd-client.so
lib/libdataitems.so
lib/libdiag.so
lib/libdisp-aba.so
lib/lib-dplmedia.so
lib/libdpmqmihal.so
lib/libdrc.so
lib/libdrmfs.so
lib/libdrmtime.so
lib/libdrplugin_client.so
lib/lib_drplugin_server.so
lib/libDRPlugin.so
lib/libdsd2pcm.so
lib/libdsi_netctrl.so
lib/libdsutils.so
lib/libevent_observer.so
lib/libfastcrc.so
lib/libfastcvadsp_stub.so
lib/libfastcvopt.so
lib/libfeedbackhandler.so
lib/libFidoCrypto_vendor.so
lib/libFIDOKeyProvisioning.so
lib/libFlacSwDec.so
lib/libflash_pmic.so
lib/libflp.so
lib/libgdtap.so
lib/libgeofence.so
lib/libgnsspps.so
lib/libgnss.so
lib/libGPreqcancel.so
lib/libGPreqcancel_svc.so
lib/libgps.utils.so
lib/libGPTEE_vendor.so
lib/libgpustats.so
lib/libgsl.so
lib/libhdcp1prov.so
lib/libhdcp2p2prov.so
lib/libhdr_tm.so
lib/libI420colorconvert.so
lib/libidl.so
lib/lib-imscmservice.so
lib/lib-imsdpl.so
lib/lib-imsqimf.so
lib/lib-imsSDP.so
lib/lib-imsxml.so
lib/libizat_client_api.so
lib/libizat_core.so
lib/libjpegdhw.so
lib/libjpegdmahw.so
lib/libjpegehw.so
lib/libjson.so
lib/libkeymasterdeviceutils.so
lib/libkeymasterprovision.so
lib/libkeymasterutils.so
lib/liblbs_core.so
lib/libllvm-glnext.so
lib/libllvm-qcom.so
lib/libllvm-qgl.so
lib/libloc_api_v02.so
lib/liblocation_api.so
lib/liblocationservice_glue.so
lib/liblocationservice.so
lib/libloc_core.so
lib/libloc_ds_api.so
lib/libloc_externalDr.so
lib/libloc_pla.so
lib/libloc_stub.so
lib/liblowi_client.so
lib/liblowi_wifihal.so
lib/liblqe.so
lib/libmdmdetect.so
lib/libmdsprpc.so
lib/libmmcamera2_c2d_module.so
lib/libmmcamera2_cpp_module.so
lib/libmmcamera2_frame_algorithm.so
lib/libmmcamera2_iface_modules.so
lib/libmmcamera2_imglib_modules.so
lib/libmmcamera2_isp_modules.so
lib/libmmcamera2_is.so
lib/libmmcamera2_mct_shimlayer.so
lib/libmmcamera2_mct.so
lib/libmmcamera2_pp_buf_mgr.so
lib/libmmcamera2_pproc_modules.so
lib/libmmcamera2_sensor_modules.so
lib/libmmcamera2_stats_algorithm.so
lib/libmmcamera2_stats_modules.so
lib/libmmcamera_chromaflash_lib.so
lib/libmmcamera_dbg.so
lib/libmmcamera_dummyalgo.so
lib/libmmcamera_eebinparse.so
lib/libmmcamera_eeprom_util.so
lib/libmmcamera_eztune_module.so
lib/libmmcamera_facedetection_lib.so
lib/libmmcamera_faceproc2.so
lib/libmmcamera_faceproc.so
lib/libmmcamera_hdr_gb_lib.so
lib/libmmcamera_hvx_add_constant.so
lib/libmmcamera_hvx_grid_sum.so
lib/libmmcamera_hvx_zzHDR.so
lib/libmmcamera_imglib_faceproc_adspstub.so
lib/libmmcamera_imglib.so
lib/libmmcamera_imx179.so
lib/libmmcamera_imx298.so
lib/libmmcamera_interface.so
lib/libmmcamera_isp_abf47.so
lib/libmmcamera_isp_aec_bg_stats47.so
lib/libmmcamera_isp_bf_stats47.so
lib/libmmcamera_isp_bg_stats46.so
lib/libmmcamera_isp_bhist_stats44.so
lib/libmmcamera_isp_black_level47.so
lib/libmmcamera_isp_bpc47.so
lib/libmmcamera_isp_cac47.so
lib/libmmcamera_isp_chroma_enhan40.so
lib/libmmcamera_isp_chroma_suppress40.so
lib/libmmcamera_isp_clamp_encoder40.so
lib/libmmcamera_isp_clamp_video40.so
lib/libmmcamera_isp_clamp_viewfinder40.so
lib/libmmcamera_isp_color_correct46.so
lib/libmmcamera_isp_color_xform_encoder46.so
lib/libmmcamera_isp_color_xform_video46.so
lib/libmmcamera_isp_color_xform_viewfinder46.so
lib/libmmcamera_isp_cs_stats46.so
lib/libmmcamera_isp_demosaic47.so
lib/libmmcamera_isp_demux40.so
lib/libmmcamera_isp_fovcrop_encoder46.so
lib/libmmcamera_isp_fovcrop_video46.so
lib/libmmcamera_isp_fovcrop_viewfinder46.so
lib/libmmcamera_isp_gamma44.so
lib/libmmcamera_isp_gic46.so
lib/libmmcamera_isp_gtm46.so
lib/libmmcamera_isp_hdr46.so
lib/libmmcamera_isp_hdr_be_stats46.so
lib/libmmcamera_isp_ihist_stats46.so
lib/libmmcamera_isp_linearization40.so
lib/libmmcamera_isp_ltm47.so
lib/libmmcamera_isp_mce40.so
lib/libmmcamera_isp_mesh_rolloff44.so
lib/libmmcamera_isp_pedestal_correct46.so
lib/libmmcamera_isp_rs_stats46.so
lib/libmmcamera_isp_scaler_encoder46.so
lib/libmmcamera_isp_scaler_video46.so
lib/libmmcamera_isp_scaler_viewfinder46.so
lib/libmmcamera_isp_sce40.so
lib/libmmcamera_isp_snr47.so
lib/libmmcamera_isp_sub_module.so
lib/libmmcamera_llvd.so
lib/libmmcamera_optizoom_lib.so
lib/libmmcamera_paaf_lib.so
lib/libmmcamera_pdafcamif.so
lib/libmmcamera_pdaf.so
lib/libmmcamera_ppbase_module.so
lib/libmmcamera_quadracfa.so
lib/libmmcamera_s5k3p8.so
lib/libmmcamera_s5k3p8sp_m24c64s_eeprom.so
lib/libmmcamera_s5k3p8sp.so
lib/libmmcamera_sony_imx179_eeprom.so
lib/libmmcamera_sony_imx298_eeprom.so
lib/libmmcamera_stillmore_lib.so
lib/libmmcamera_sw2d_lib.so
lib/libmmcamera_thread_services.so
lib/libmmcamera_tintless_algo.so
lib/libmmcamera_tintless_bg_pca_algo.so
lib/libmmcamera_trueportrait_lib.so
lib/libmmcamera_tuning_lookup.so
lib/libmmcamera_tuning.so
lib/libmmcamera_ubifocus_lib.so
lib/libmm-color-convertor.so
lib/libmm-disp-apis.so
lib/libmm-hdcpmgr.so
lib/libmmi_jni.so
lib/libmmi.so
lib/libmmjpeg_interface.so
lib/libmmjpeg.so
lib/libmmosal_proprietary.so
lib/libmm-qdcm.so
lib/libmmqjpeg_codec.so
lib/libmmqjpegdma.so
lib/libnetmgr.so
lib/libois_rohm_bu63165gwl.so
lib/libOmxAacDec.so
lib/libOmxAlacDec.so
lib/libOmxAlacDecSw.so
lib/libOmxAmrDec.so
lib/libOmxAmrwbplusDec.so
lib/libOmxApeDec.so
lib/libOmxApeDecSw.so
lib/libOmxDsdDec.so
lib/libomx-dts.so
lib/libOmxEvrcDec.so
lib/libOmxQcelp13Dec.so
lib/libOmxVideoDSMode.so
lib/libOmxVpp.so
lib/libOmxWmaDec.so
lib/libOpenCL.so
lib/liboptizoom.so
lib/libpdmapper.so
lib/libperfgluelayer.so
lib/libperipheral_client.so
lib/libpvr.so
lib/libqcci_legacy.so
lib/libqcmaputils.so
lib/libqdi.so
lib/libqdp.so
lib/libqisl.so
lib/libqmi_cci.so
lib/libqmi_client_helper.so
lib/libqmi_client_qmux.so
lib/libqmi_common_so.so
lib/libqmi_csi.so
lib/libqmi_encdec.so
lib/libqmiservices.so
lib/libqmi.so
lib/libqomx_jpegdec.so
lib/libqomx_jpegenc_pipe.so
lib/libqomx_jpegenc.so
lib/libQSEEComAPI.so
lib/libQTEEConnector_vendor.so
lib/libqtigef.so
lib/libqti-iopd-client.so
lib/libqti-iopd.so
lib/libqti-perfd-client.so
lib/libqti-perfd.so
lib/libqti-util.so
lib/libquipc_os_api.so
lib/libremosaic_daemon.so
lib/libremosaiclib.so
lib/libremosaic_tuning.so
lib/lib_remote_simlock.so
lib/libril-qc-ltedirectdisc.so
lib/libril-qc-qmi-1.so
lib/libril-qc-radioconfig.so
lib/libril-qcril-hook-oem.so
lib/librilqmiservices.so
lib/librmp.so
lib/librpmb.so
lib/librs_adreno_sha1.so
lib/librs_adreno.so
lib/libRSDriver_adreno.so
lib/lib-rtpcommon.so
lib/lib-rtpcore.so
lib/lib-rtpdaemoninterface.so
lib/lib-rtpsl.so
lib/libscalar.so
lib/libscveBlobDescriptor.so
lib/libscveBlobDescriptor_stub.so
lib/libscveCommon.so
lib/libscveCommon_stub.so
lib/libscveImageCorrection.so
lib/libscveObjectSegmentation.so
lib/libscveObjectTracker.so
lib/libscveObjectTracker_stub.so
lib/libscvePanorama_lite.so
lib/libscvePanorama.so
lib/libsdm-color.so
lib/libsdm-diag.so
lib/libsdm-disp-vndapis.so
lib/libsdmextension.so
lib/libsd_sdk_display.so
lib/libsdsprpc.so
lib/lib-sec-disp.so
lib/libSecureUILib.so
lib/libsecureui.so
lib/libsecureuisvc_jni.so
lib/libsecureui_svcsock.so
lib/libseemore.so
lib/libsensor1.so
lib/libsensor_reg.so
lib/libsensor_thresh.so
lib/libsensor_user_cal.so
lib/libsettings.so
lib/libsi.so
lib/libslimclient.so
lib/libsmemlog.so
lib/libsmwrapper.so
lib/libSonyIMX298PdafLibrary.so
lib/libssd.so
lib/libStDrvInt.so
lib/libstreamparser.so
lib/libsubsystem_control.so
lib/libSubSystemShutdown.so
lib/libsurround_3mic_proc.so
lib/libsystem_health_mon.so
lib/libthermalclient.so
lib/libtime_genoff.so
lib/libTimeService.so
lib/libtinyxml2_1.so
lib/libtinyxml.so
lib/libts_detected_face_hal.so
lib/libts_face_beautify_hal.so
lib/libtzdrmgenprov.so
lib/libubifocus.so
lib/libUBWC.so
lib/lib-uceservice.so
lib/libulp2.so
lib/libvideoutils.so
lib/libvpphvx.so
lib/libvpplibrary.so
lib/libvqzip.so
lib/libwfdcommonutils_proprietary.so
lib/libwfdhaldsmanager.so
lib/libwfdhdcpcp.so
lib/libwfdmmservice.so
lib/libwfdmodulehdcpsession.so
lib/libwms.so
lib/libwqe.so
lib/libxml.so
lib/libxtadapter.so
lib/libxtwifi_ulp_adaptor.so
lib/mmi_audio.so
lib/mmi_battery.so
lib/mmi_bluetooth.so
lib/mmi_camera.so
lib/mmi_cpu.so
lib/mmi_flashlight.so
lib/mmi_fm.so
lib/mmi_gps.so
lib/mmi_headset.so
lib/mmi_key.so
lib/mmi_lcd.so
lib/mmi_light.so
lib/mmi_memory.so
lib/mmi_nfc.so
lib/mmi_power.so
lib/mmi_sensor.so
lib/mmi_sim.so
lib/mmi_storage.so
lib/mmi_sysinfo.so
lib/mmi_telephone.so
lib/mmi_touch.so
lib/mmi_vibrator.so
lib/mmi_wifi.so
lib/rfsa/adsp/libadsp_fd_skel.so
lib/rfsa/adsp/libadsp_hvx_add_constant.so
lib/rfsa/adsp/libadsp_hvx_skel.so
lib/rfsa/adsp/libadsp_hvx_stats.so
lib/rfsa/adsp/libadsp_hvx_zzhdr_BGGR.so
lib/rfsa/adsp/libadsp_hvx_zzhdr_RGGB.so
lib/rfsa/adsp/libapps_mem_heap.so
lib/rfsa/adsp/libdspCV_skel.so
lib/rfsa/adsp/libfastcvadsp_skel.so
lib/rfsa/adsp/libfastcvadsp.so
lib/rfsa/adsp/libscveBlobDescriptor_skel.so
lib/rfsa/adsp/libscveT2T_skel.so
lib/rfsa/adsp/libvpp_frc.so
lib/rfsa/adsp/libvpp_svc_skel.so
lib/rfsa/adsp/us-syncproximity.so
lib/sensor_calibrate.so
lib/sensors.ssc.so
lib/soundfx/libasphere.so
lib/soundfx/libqcbassboost.so
lib/soundfx/libqcompostprocbundle.so
lib/soundfx/libqcomvisualizer.so
lib/soundfx/libqcomvoiceprocessing.so
lib/soundfx/libqcreverb.so
lib/soundfx/libqcvirt.so
lib/soundfx/libshoebox.so
lib/vendor.display.color@1.0_vendor.so
lib/vendor.display.postproc@1.0_vendor.so
lib/vendor.qti.esepowermanager@1.0_vendor.so
lib/vendor.qti.gnss@1.0_vendor.so
lib/vendor.qti.hardware.alarm@1.0.so
lib/vendor.qti.hardware.fingerprint@1.0.so
lib/vendor.qti.hardware.fm@1.0_vendor.so
lib/vendor.qti.hardware.iop@1.0_vendor.so
lib/vendor.qti.hardware.perf@1.0_vendor.so
lib/vendor.qti.hardware.qteeconnector@1.0_vendor.so
lib/vendor.qti.hardware.radio.am@1.0_vendor.so
lib/vendor.qti.hardware.radio.ims@1.0_vendor.so
lib/vendor.qti.hardware.radio.lpa@1.0_vendor.so
lib/vendor.qti.hardware.radio.qcrilhook@1.0_vendor.so
lib/vendor.qti.hardware.radio.qtiradio@1.0_vendor.so
lib/vendor.qti.hardware.radio.uim@1.0_vendor.so
lib/vendor.qti.hardware.radio.uim_remote_client@1.0_vendor.so
lib/vendor.qti.hardware.radio.uim_remote_server@1.0_vendor.so
lib/vendor.qti.imsrtpservice@1.0-service-Impl.so
lib/vendor.qti.imsrtpservice@1.0_vendor.so
lib/vendor.qti.voiceprint@1.0.so
lib64/com.qualcomm.qti.ant@1.0_vendor.so
lib64/com.qualcomm.qti.bluetooth_audio@1.0_vendor.so
lib64/com.qualcomm.qti.dpm.api@1.0_vendor.so
lib64/com.qualcomm.qti.imscmservice@1.0_vendor.so
lib64/com.qualcomm.qti.wifidisplayhal@1.0-halimpl.so
lib64/com.qualcomm.qti.wifidisplayhal@1.0-impl.so
lib64/com.qualcomm.qti.wifidisplayhal@1.0_vendor.so
lib64/com.quicinc.cne.api@1.0.so
lib64/com.quicinc.cne.constants@1.0.so
lib64/com.quicinc.cne.constants@2.0.so
lib64/com.quicinc.cne.server@1.0.so
lib64/com.quicinc.cne.server@2.0.so
lib64/egl/eglSubDriverAndroid.so
lib64/egl/libEGL_adreno.so
lib64/egl/libGLESv1_CM_adreno.so
lib64/egl/libGLESv2_adreno.so
lib64/egl/libq3dtools_adreno.so
lib64/egl/libq3dtools_esx.so
lib64/egl/libQTapGLES.so
lib64/hw/activity_recognition.msm8996.so
lib64/hw/android.hardware.audio@2.0-impl.so
lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so
lib64/hw/android.hardware.gnss@1.0-impl-qti.so
lib64/hw/android.hardware.renderscript@1.0-impl.so
lib64/hw/android.hardware.sensors@1.0-impl.so
lib64/hw/android.hardware.tests.libhwbinder@1.0-impl.so
lib64/hw/com.qualcomm.qti.ant@1.0-impl.so
lib64/hw/gatekeeper.msm8996.so
lib64/hw/keystore.msm8996.so
lib64/hw/lights.msm8996.so
lib64/hw/sound_trigger.primary.msm8996.so
lib64/hw/vendor.qti.esepowermanager@1.0-impl.so
lib64/hw/vendor.qti.gnss@1.0-impl.so
lib64/hw/vendor.qti.hardware.fm@1.0-impl.so
lib64/hw/vendor.qti.hardware.iop@1.0-impl.so
lib64/hw/vendor.qti.hardware.qteeconnector@1.0-impl.so
lib64/hw/vulkan.msm8996.so
lib64/libacdb-fts.so
lib64/libacdbloader.so
lib64/libacdbmapper.so
lib64/libacdbrtac.so
lib64/libadiertac.so
lib64/libadreno_utils.so
lib64/libadsp_default_listener.so
lib64/libadsprpc.so
lib64/libAlacSwDec.so
lib64/libalarmservice_jni.so
lib64/libApeSwDec.so
lib64/libAR_jni.so
lib64/libaudcal.so
lib64/libaudioalsa.so
lib64/libaudio_log_utils.so
lib64/libbccQTI.so
lib64/libbt-hidlclient.so
lib64/libbtnv.so
lib64/libbt-vendor.so
lib64/libC2D2.so
lib64/libc2d30-a3xx.so
lib64/libc2d30-a4xx.so
lib64/libc2d30-a5xx.so
lib64/libc2d30_bltlib.so
lib64/libc2dcolorconvert.so
lib64/libCB.so
lib64/libcdsprpc.so
lib64/libcld80211.so
lib64/libcneapiclient.so
lib64/libcneoplookup.so
lib64/libcneqmiutils.so
lib64/libcne.so
lib64/libconfigdb.so
lib64/libcsd-client.so
lib64/libdataitems.so
lib64/libdiag.so
lib64/libdisp-aba.so
lib64/lib-dplmedia.so
lib64/libdpmqmihal.so
lib64/libdrmfs.so
lib64/libdrmtime.so
lib64/libdrplugin_client.so
lib64/lib_drplugin_server.so
lib64/libDRPlugin.so
lib64/libdsi_netctrl.so
lib64/libdsutils.so
lib64/libevent_observer.so
lib64/libfastcrc.so
lib64/libfastcvadsp_stub.so
lib64/libfastcvopt.so
lib64/libfeedbackhandler.so
lib64/libFidoCrypto_vendor.so
lib64/libFIDOKeyProvisioning.so
lib64/libFlacSwDec.so
lib64/libflp.so
lib64/libgdtap.so
lib64/libgeofence.so
lib64/libgnsspps.so
lib64/libgnss.so
lib64/libGPreqcancel.so
lib64/libGPreqcancel_svc.so
lib64/libgps.utils.so
lib64/libGPTEE_vendor.so
lib64/libgpustats.so
lib64/libgsl.so
lib64/libhdcp1prov.so
lib64/libhdcp2p2prov.so
lib64/libhdr_tm.so
lib64/libI420colorconvert.so
lib64/libidl.so
lib64/lib-imscmservice.so
lib64/lib-imsdpl.so
lib64/lib-imsqimf.so
lib64/lib-imsSDP.so
lib64/lib-imsxml.so
lib64/libizat_client_api.so
lib64/libizat_core.so
lib64/libjson.so
lib64/libkeymasterdeviceutils.so
lib64/libkeymasterprovision.so
lib64/libkeymasterutils.so
lib64/libkeystore-engine-wifi-hidl.so
lib64/libkeystore-wifi-hidl.so
lib64/liblbs_core.so
lib64/libllvm-glnext.so
lib64/libllvm-qcom.so
lib64/libllvm-qgl.so
lib64/libloc_api_v02.so
lib64/liblocation_api.so
lib64/liblocationservice_glue.so
lib64/liblocationservice.so
lib64/libloc_core.so
lib64/libloc_ds_api.so
lib64/libloc_externalDr.so
lib64/libloc_pla.so
lib64/libloc_stub.so
lib64/liblowi_client.so
lib64/liblowi_wifihal.so
lib64/liblqe.so
lib64/libmdmdetect.so
lib64/libmdmimgload.so
lib64/libmdsprpc.so
lib64/libmmcamera2_frame_algorithm.so
lib64/libmmcamera2_is.so
lib64/libmmcamera2_stats_algorithm.so
lib64/libmmcamera_dbg.so
lib64/libmmcamera_tintless_algo.so
lib64/libmmcamera_tintless_bg_pca_algo.so
lib64/libmm-color-convertor.so
lib64/libmm-disp-apis.so
lib64/libmm-hdcpmgr.so
lib64/libmmi_jni.so
lib64/libmmi.so
lib64/libmmosal_proprietary.so
lib64/libmm-qdcm.so
lib64/libnetmgr.so
lib64/libOmxAacDec.so
lib64/libOmxAlacDec.so
lib64/libOmxAlacDecSw.so
lib64/libOmxAmrDec.so
lib64/libOmxAmrwbplusDec.so
lib64/libOmxApeDec.so
lib64/libOmxApeDecSw.so
lib64/libOmxEvrcDec.so
lib64/libOmxQcelp13Dec.so
lib64/libOmxVpp.so
lib64/libOmxWmaDec.so
lib64/libOpenCL.so
lib64/liboptizoom.so
lib64/libpdmapper.so
lib64/libperfgluelayer.so
lib64/libperipheral_client.so
lib64/libpvr.so
lib64/libqcci_legacy.so
lib64/libqcmaputils.so
lib64/libqcproximity.so
lib64/libqdi.so
lib64/libqdp.so
lib64/libqisl.so
lib64/libqmi_cci.so
lib64/libqmi_client_helper.so
lib64/libqmi_client_qmux.so
lib64/libqmi_common_so.so
lib64/libqmi_csi.so
lib64/libqmi_encdec.so
lib64/libqmiservices.so
lib64/libqmi.so
lib64/libQSEEComAPI.so
lib64/libQTEEConnector_vendor.so
lib64/libqtigef.so
lib64/libqti-gt-prop.so
lib64/libqti-iopd-client.so
lib64/libqti-iopd.so
lib64/libqti-perfd-client.so
lib64/libqti-perfd.so
lib64/libqti-util.so
lib64/libquipc_os_api.so
lib64/libremosaic_daemon.so
lib64/libremosaiclib.so
lib64/libremosaic_tuning.so
lib64/lib_remote_simlock.so
lib64/libril-qc-ltedirectdisc.so
lib64/libril-qc-qmi-1.so
lib64/libril-qc-radioconfig.so
lib64/libril-qcril-hook-oem.so
lib64/librilqmiservices.so
lib64/librmp.so
lib64/librpmb.so
lib64/librs_adreno_sha1.so
lib64/librs_adreno.so
lib64/libRSDriver_adreno.so
lib64/lib-rtpcommon.so
lib64/lib-rtpcore.so
lib64/lib-rtpdaemoninterface.so
lib64/lib-rtpsl.so
lib64/libscalar.so
lib64/libscveBlobDescriptor.so
lib64/libscveBlobDescriptor_stub.so
lib64/libscveCommon.so
lib64/libscveCommon_stub.so
lib64/libscveImageCorrection.so
lib64/libscveObjectSegmentation.so
lib64/libscveObjectTracker.so
lib64/libscveObjectTracker_stub.so
lib64/libscvePanorama_lite.so
lib64/libscvePanorama.so
lib64/libsdm-color.so
lib64/libsdm-diag.so
lib64/libsdm-disp-vndapis.so
lib64/libsdmextension.so
lib64/libsd_sdk_display.so
lib64/libsdsprpc.so
lib64/lib-sec-disp.so
lib64/libSecureUILib.so
lib64/libsecureui.so
lib64/libsecureuisvc_jni.so
lib64/libsecureui_svcsock.so
lib64/libseemore.so
lib64/libsensor1.so
lib64/libsensor_reg.so
lib64/libsensor_thresh.so
lib64/libsensor_user_cal.so
lib64/libsettings.so
lib64/libsi.so
lib64/libslimclient.so
lib64/libsmemlog.so
lib64/libssd.so
lib64/libStDrvInt.so
lib64/libstreamparser.so
lib64/libsubsystem_control.so
lib64/libSubSystemShutdown.so
lib64/libsystem_health_mon.so
lib64/libthermalclient.so
lib64/libthermalioctl.so
lib64/libtime_genoff.so
lib64/libTimeService.so
lib64/libtinyxml2_1.so
lib64/libtinyxml.so
lib64/libts_detected_face_hal.so
lib64/libts_face_beautify_hal.so
lib64/libtzdrmgenprov.so
lib64/libubifocus.so
lib64/libUBWC.so
lib64/lib-uceservice.so
lib64/libulp2.so
lib64/libusutils.so
lib64/libvideoutils.so
lib64/libvpphvx.so
lib64/libvpplibrary.so
lib64/libwfdcommonutils_proprietary.so
lib64/libwfdhaldsmanager.so
lib64/libwfdhdcpcp.so
lib64/libwfdmmservice.so
lib64/libwfdmodulehdcpsession.so
lib64/libwifi-hal-qcom.so
lib64/libwifi-hal.so
lib64/libwms.so
lib64/libwpa_client.so
lib64/libwqe.so
lib64/libxml.so
lib64/libxtadapter.so
lib64/libxtwifi_ulp_adaptor.so
lib64/mmi_audio.so
lib64/mmi_battery.so
lib64/mmi_bluetooth.so
lib64/mmi_cpu.so
lib64/mmi_flashlight.so
lib64/mmi_fm.so
lib64/mmi_gps.so
lib64/mmi_headset.so
lib64/mmi_key.so
lib64/mmi_lcd.so
lib64/mmi_light.so
lib64/mmi_memory.so
lib64/mmi_nfc.so
lib64/mmi_power.so
lib64/mmi_sensor.so
lib64/mmi_sim.so
lib64/mmi_storage.so
lib64/mmi_sysinfo.so
lib64/mmi_telephone.so
lib64/mmi_touch.so
lib64/mmi_vibrator.so
lib64/mmi_wifi.so
lib64/sensor_calibrate.so
lib64/sensors.ssc.so
lib64/soundfx/libasphere.so
lib64/soundfx/libqcbassboost.so
lib64/soundfx/libqcompostprocbundle.so
lib64/soundfx/libqcomvisualizer.so
lib64/soundfx/libqcomvoiceprocessing.so
lib64/soundfx/libqcreverb.so
lib64/soundfx/libqcvirt.so
lib64/soundfx/libshoebox.so
lib64/vendor.display.color@1.0_vendor.so
lib64/vendor.display.postproc@1.0_vendor.so
lib64/vendor.qti.esepowermanager@1.0_vendor.so
lib64/vendor.qti.gnss@1.0_vendor.so
lib64/vendor.qti.hardware.alarm@1.0.so
lib64/vendor.qti.hardware.fingerprint@1.0.so
lib64/vendor.qti.hardware.fm@1.0_vendor.so
lib64/vendor.qti.hardware.iop@1.0_vendor.so
lib64/vendor.qti.hardware.perf@1.0_vendor.so
lib64/vendor.qti.hardware.qteeconnector@1.0_vendor.so
lib64/vendor.qti.hardware.radio.am@1.0_vendor.so
lib64/vendor.qti.hardware.radio.atcmdfwd@1.0_vendor.so
lib64/vendor.qti.hardware.radio.ims@1.0_vendor.so
lib64/vendor.qti.hardware.radio.lpa@1.0_vendor.so
lib64/vendor.qti.hardware.radio.qcrilhook@1.0_vendor.so
lib64/vendor.qti.hardware.radio.qtiradio@1.0_vendor.so
lib64/vendor.qti.hardware.radio.uim@1.0_vendor.so
lib64/vendor.qti.hardware.radio.uim_remote_client@1.0_vendor.so
lib64/vendor.qti.hardware.radio.uim_remote_server@1.0_vendor.so
lib64/vendor.qti.imsrtpservice@1.0-service-Impl.so
lib64/vendor.qti.imsrtpservice@1.0_vendor.so
lib64/vendor.qti.voiceprint@1.0.so
radio/qcril_database/qcril.db
lib/libmmcamera2_q3a_core.so
"

for i in ${vendor_list}
do
  adb pull /system/vendor/${i} ${PREBUILT_PATH}vendor/${i}
done

framework_list="
com.qti.snapdragon.sdk.display.jar  
dpmapi.jar                     
qmapbridge.jar                   
tcmclient.jar
embmslibrary.jar               
izat.xt.srv.jar                
cneapiclient.jar                     
com.quicinc.cne.jar                 
com.qti.dpmframework.jar              
oem-services.jar  
"

for i in ${framework_list}
do
  adb pull /system/framework/${i} ${PREBUILT_PATH}framework/${i}
done

xbin_list="
antradio_app
"

for i in ${xbin_list}
do
  adb pull /system/xbin/${i} ${PREBUILT_PATH}xbin/${i}
done

sbin_list="
dashd
"

for i in ${sbin_list}
do
  adb pull /sbin/${i} ${PREBUILT_PATH}sbin/${i}
done
